---
- name: Check APT contrib
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      apt-cache policy | grep {{ ansible_distribution_release }}/contrib
    executable: /bin/bash
  register: all_result_check_contrib
  changed_when: all_result_check_contrib.rc == 1
  failed_when: all_result_check_contrib.rc > 1
- name: Enable contrib APT
  become: true
  ansible.builtin.command: apt-add-repository --yes contrib
  when: all_result_check_contrib.rc == 1
  changed_when: true

- name: Check APT non-free
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      apt-cache policy | grep {{ ansible_distribution_release }}/non-free
    executable: /bin/bash
  register: all_result_check_nonfree
  changed_when: all_result_check_nonfree.rc == 1
  failed_when: all_result_check_nonfree.rc > 1
- name: Enable non-free APT
  become: true
  ansible.builtin.command: apt-add-repository --yes non-free
  when: all_result_check_nonfree.rc == 1
  changed_when: true

- name: Check APT non-free-firmware
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      apt-cache policy | grep {{ ansible_distribution_release }}/non-free-firmware
    executable: /bin/bash
  register: all_result_check_nonfreefirmware
  changed_when: all_result_check_nonfreefirmware.rc == 1
  failed_when: all_result_check_nonfreefirmware.rc > 1
- name: Enable non-free-firmware APT
  become: true
  ansible.builtin.command: apt-add-repository --yes non-free-firmware
  when: all_result_check_nonfreefirmware.rc == 1
  changed_when: true

- name: Install commonly used dependencies
  become: true
  register: all_result
  retries: 3
  delay: 3
  until: all_result is not failed
  ansible.builtin.apt:
    name:
      - acl
      - apparmor-profiles
      - apparmor-utils
      - bash
      - ca-certificates
      - cifs-utils
      - cmake
      - curl
      - dnsutils
      - file
      - git
      - glances
      - htop
      - iputils-tracepath
      - jq
      - keychain
      - kitty-terminfo
      - lshw
      - lsof
      - man-db
      - ncdu
      - nmap
      - openssh-client
      - psmisc
      - python3
      - python3-pip
      - python3-psycopg2
      - ripgrep
      - rsync
      - samba
      - smbclient
      - snmp
      - strace
      - tzdata
      - unrar
      - unzip
      - vim
      - wakeonlan
      - wget
      - whois
      - wireguard
      - wireguard-tools
      - zsh
    update_cache: true
