---
- name: Install Debian Sources Configuration
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/etc/apt/sources.list.d/debian.sources"
    dest: /etc/apt/sources.list.d/debian.sources
    mode: "0o644"
    owner: root
    group: root

- name: Delete Legacy APT Configuration
  become: true
  ansible.builtin.file:
    path: /etc/apt/sources.list
    state: absent

- name: Install commonly used dependencies
  become: true
  register: all_result
  retries: 3
  delay: 3
  until: all_result is not failed
  ansible.builtin.apt:
    name:
      - acl
      - apparmor-profiles
      - apparmor-utils
      - bash
      - ca-certificates
      - cifs-utils
      - cmake
      - curl
      - dnsutils
      - file
      - git
      - glances
      - htop
      - iputils-tracepath
      - jq
      - keychain
      - kitty-terminfo
      - lshw
      - lsof
      - man-db
      - ncdu
      - nmap
      - openssh-client
      - psmisc
      - python3
      - python3-pip
      - python3-psycopg2
      - ripgrep
      - rsync
      - samba
      - smbclient
      - snmp
      - strace
      - tzdata
      - unrar
      - unzip
      - vim
      - wakeonlan
      - wget
      - whois
      - wireguard
      - wireguard-tools
      - zsh
    update_cache: true
