---
- name: Disable Power-Save Garbage 1
  become: true
  ansible.builtin.dconf:
    key: /org/gnome/settings-daemon/plugins/power
    value: "['sleep-inactive-ac-type', 'nothing']"
- name: Disable Power-Save Garbage 2
  become: true
  ansible.builtin.dconf:
    key: /org/gnome/settings-daemon/plugins/power
    value: "['sleep-inactive-battery-type', 'suspend']"
- name: Disable Power-Save Garbage 3
  become: true
  ansible.builtin.shell:
    cmd: tuned-adm profile throughput-performance

- name: Install systemd-resolved
  become: true
  ansible.builtin.apt:
    name:
      - systemd-resolved

- name: Enable systemd-resolved
  become: true
  ansible.builtin.systemd:
    name: systemd-resolved
    state: started
    enabled: true

# Ideally, just reboot fresh machines after this is applied. Then re-run.
- name: Enable systemd-networkd
  become: true
  ansible.builtin.systemd:
    name: systemd-networkd
    state: started
    enabled: true

- name: Write noswap systemd service config file
  become: true
  ansible.builtin.template:
    src: noswap.service.j2
    dest: /etc/systemd/system/noswap.service
    owner: root
    group: root
    mode: "0o644"
  notify: Enable noswap service

- name: Generate /etc/hosts
  become: true
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: "0o644"

- name: APT
  ansible.builtin.include_tasks: apt.yml
# - name: DNS
#   ansible.builtin.include_tasks: dns.yml

- name: Set default editor
  become: true
  community.general.alternatives:
    name: editor
    path: /usr/bin/vim

- name: Age
  ansible.builtin.include_tasks: age.yml
- name: NodeJs
  ansible.builtin.include_tasks: nodejs.yml
- name: SOPS
  ansible.builtin.include_tasks: sops.yml
