---
- name: Gather Facts
  ansible.builtin.gather_facts:

- name: Install commonly used dependencies
  become: true
  ansible.builtin.apt:
    name:
      - bash
      - ca-certificates
      - curl
      - dnsutils
      - git
      - htop
      - iputils-tracepath
      - keychain
      - lshw
      - man-db
      - ncdu
      - nmap
      - openssh-client
      - python3
      - python3-pip
      - tzdata
      - vim
      - wget
      - zsh
    update_cache: true

- name: Generate SSH key
  community.crypto.openssh_keypair:
    path: ~/.ssh/id_ed25519
    force: false
    regenerate: never
    mode: 0600

- name: Set default editor
  become: true
  community.general.alternatives:
    name: editor
    path: /usr/bin/vim

- name: Copy .bashrc
  ansible.builtin.copy:
    src: "{{ role_path }}/files/home/.bashrc"
    dest: ~/.bashrc
- name: Copy .profile
  ansible.builtin.copy:
    src: "{{ role_path }}/files/home/.profile"
    dest: ~/.profile

- name: "Ensure default config directory exists: htop"
  file: 
    path: ~/.config/htop/
    state: directory
- name: "Install default configs: htop"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/home/.config/htop/htoprc"
    dest: ~/.config/htop/htoprc

- name: Ensure working directory exists
  ansible.builtin.file:
    path: "{{ directory_downloads }}"
    state: directory
    owner: "{{ ansible_user }}"

- name: Download Oh My Zsh installer
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: "{{ directory_downloads }}/install-ohmyzsh.sh"
    mode: 0744
- name: Execute the installer
  ansible.builtin.shell: 
    cmd: "{{ directory_downloads }}/install-ohmyzsh.sh --unattended"
    creates: ~/.oh-my-zsh/
- name: Install Powerlevel10k theme
  ansible.builtin.git:
    repo: "https://github.com/romkatv/powerlevel10k.git"
    dest: ~/.oh-my-zsh/themes/powerlevel10k
    depth: 1
- name: Install ZSH auto-suggestions plugin
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: ~/.oh-my-zsh/plugins/zsh-autosuggestions
    depth: 1
- name: Install ZSH syntax highlighting plugin
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: ~/.oh-my-zsh/plugins/zsh-syntax-highlighting
    depth: 1
- name: Install .zshrc
  ansible.builtin.template:
    src: home/.zshrc.j2
    dest: ~/.zshrc
    mode: 0600
    
- name: Install powerlevel10k config
  ansible.builtin.copy:
    src: "{{ role_path }}/files/home/.p10k.zsh"
    dest: ~/.p10k.zsh

- name: Set login shell
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh

- name: Install Meslo Nerd Font patched for Powerlevel10k
  ansible.builtin.copy:
    src: "{{ role_path }}/files/home/.local/share/fonts/"
    dest: ~/.local/share/fonts/
    mode: 0644

- include_tasks: age.yml
- include_tasks: coding-environment.yml
- include_tasks: keyboard.yml
- include_tasks: nodejs.yml
- include_tasks: sops.yml
- include_tasks: terraform.yml
