---
- name: Install systemd-resolved
  become: true
  ansible.builtin.apt:
    name:
      - systemd-resolved

- name: Enable systemd-resolved
  become: true
  ansible.builtin.systemd:
    name: systemd-resolved
    state: started
    enabled: true

- name: Enable systemd-networkd
  become: true
  ansible.builtin.systemd:
    name: systemd-networkd
    state: started
    enabled: true

- name: Write noswap systemd service config file
  become: true
  ansible.builtin.template:
    src: noswap.service.j2
    dest: /etc/systemd/system/noswap.service
    owner: root
    group: root
    mode: "0o644"
  notify: Enable noswap service

- name: Generate /etc/hosts
  become: true
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: "0o644"

- name: Set default editor
  become: true
  community.general.alternatives:
    name: editor
    path: /usr/bin/vim

- name: APT
  ansible.builtin.include_tasks: apt.yml
# - name: DNS
#   ansible.builtin.include_tasks: dns.yml

- name: Age
  ansible.builtin.include_tasks: age.yml
- name: Coding environment
  ansible.builtin.include_tasks: coding-environment.yml
- name: NodeJS
  ansible.builtin.include_tasks: nodejs.yml
- name: SOPS
  ansible.builtin.include_tasks: sops.yml
- name: Terraform
  ansible.builtin.include_tasks: terraform.yml
