---
- name: Write noswap systemd service config file
  become: true
  ansible.builtin.template:
    src: noswap.service.j2
    dest: /etc/systemd/system/noswap.service
    owner: root
    group: root
    mode: "0o644"
  notify: Enable noswap service

- name: Generate /etc/hosts
  become: true
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: "0o644"

- name: Update and upgrade apt packages
  become: true
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 86400

- name: Install commonly used dependencies
  become: true
  ansible.builtin.apt:
    name:
      - apparmor-profiles
      - apparmor-utils
      - bash
      - ca-certificates
      - cifs-utils
      - cmake
      - curl
      - dnsutils
      - file
      - git
      - htop
      - iputils-tracepath
      - jq
      - keychain
      - kitty-terminfo
      - lshw
      - lsof
      - man-db
      - ncdu
      - nmap
      - openssh-client
      - psmisc
      - python3
      - python3-pip
      - python3-psycopg2
      - ripgrep
      - snmp
      - software-properties-common
      - strace
      - tzdata
      - unrar
      - unzip
      - vim
      - wakeonlan
      - wget
      - whois
      - wireguard
      - wireguard-tools
      - wpasupplicant
      - zsh
    update_cache: true

- name: Set default editor
  become: true
  community.general.alternatives:
    name: editor
    path: /usr/bin/vim

- name: Age
  ansible.builtin.include_tasks: age.yml
- name: Coding environment
  ansible.builtin.include_tasks: coding-environment.yml
- name: NodeJS
  ansible.builtin.include_tasks: nodejs.yml
- name: SOPS
  ansible.builtin.include_tasks: sops.yml
- name: Terraform
  ansible.builtin.include_tasks: terraform.yml
