---
- name: Gather facts
  ansible.builtin.gather_facts:

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 86400

- name: Install commonly used dependencies
  become: true
  ansible.builtin.apt:
    name:
      - apparmor-profiles
      - apparmor-utils
      - bash
      - ca-certificates
      - cifs-utils
      - cmake
      - curl
      - dnsutils
      - file
      - git
      - htop
      - iputils-tracepath
      - jq
      - keychain
      - kitty-terminfo
      - lshw
      - lsof
      - man-db
      - ncdu
      - nmap
      - openssh-client
      - python3
      - python3-pip
      - ripgrep
      - software-properties-common
      - tzdata
      - unzip
      - vim
      - wakeonlan
      - wget
      - whois
      - wireguard
      - zsh
    update_cache: true

- name: Set default editor
  become: true
  community.general.alternatives:
    name: editor
    path: /usr/bin/vim

- include_tasks: age.yml
- include_tasks: coding-environment.yml
- include_tasks: nodejs.yml
- include_tasks: sops.yml
- include_tasks: terraform.yml
