---
- name: Ensure downloads exists
  ansible.builtin.file:
    path: "{{ directory_downloads }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "u=rwX,g=rX,o="
    recurse: false

- name: Download SOPS binary
  register: all_result
  retries: 3
  delay: 3
  until: all_result is not failed
  ansible.builtin.get_url:
    url: "https://github.com/getsops/sops/releases/download/v{{ version_sops }}/sops-v{{ version_sops }}.linux"
    dest: "{{ directory_downloads }}"
    mode: "0o750"

- name: Copy SOPS binary to destination directory
  become: true
  ansible.builtin.copy:
    src: "{{ directory_downloads }}/sops-v{{ version_sops }}.linux"
    dest: /usr/local/bin/sops
    mode: "0o755"
    owner: root
    group: root
    remote_src: true
