- name: Install APT key
  become: true
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    keyring: "{{ directory_keyrings }}/hashicorp-archive-keyring.gpg"
    state: present
- name: Add Hashicorp Repository
  become: true
  ansible.builtin.apt_repository:
    repo: |
      deb [signed-by={{ directory_keyrings }}/hashicorp-archive-keyring.gpg]
      https://apt.releases.hashicorp.com bookworm main
    state: present

- name: Install Terraform
  become: true
  ansible.builtin.apt:
    name:
      - terraform
    state: present
    update_cache: true
