---
- name: Create groups
  become: true
  register: _groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
    system: true
  loop: "{{ radarr_groups }}"

- name: Ensure {{ ansible_user }} is a group member
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ radarr_groups }}"
    append: true

- name: Create user
  become: true
  register: _user
  ansible.builtin.user:
    comment: "{{ radarr_name }}"
    create_home: false
    group: "{{ _groups.results[0].gid }}"
    groups: "{{ radarr_groups }}"
    home: "{{ radarr_basedir }}"
    name: "{{ radarr_id }}"
    password: "!"
    shell: "/usr/sbin/nologin"
    system: true


- name: Ensure working directory exists
  become: true
  ansible.builtin.file:
    path: "{{ radarr_basedir }}"
    state: directory
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"

- name: Ensure directories exist
  become: true
  ansible.builtin.file:
    path: "{{ radarr_basedir }}/{{ item }}"
    state: directory
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"
  loop:
    - config


- name: Copy configuration
  become: true
  ansible.builtin.template:
    src: "config.xml.j2"
    dest: "{{ radarr_basedir }}/config/config.xml"
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"
    mode: 0644


- name: Copy service files
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ directory_systemd }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - radarr-exporter.service
    - radarr-main.service
    - radarr.service

- name: Enable and check service
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    name: radarr
    state: restarted
