---
- name: Ensure working directory exists
  become: true
  ansible.builtin.file:
    path: "{{ radarr_basedir }}"
    state: directory
    owner: "{{ ansible_user }}"

- name: Ensure config directory exists
  become: true
  ansible.builtin.file:
    path: "{{ radarr_basedir }}/config"
    state: directory
    owner: "{{ ansible_user }}"

- name: Copy radarr service file
  become: true
  ansible.builtin.template:
    src: radarr.service.j2
    dest: "{{ directory_systemd }}/radarr.service"
    owner: root
    group: root
    mode: 0644

- name: Enable and check radarr service
  become: true
  ansible.builtin.systemd:
    name: radarr
    daemon_reload: true
    state: restarted
    enabled: true
