#!/usr/bin/env ansible-playbook

---
- name: Wait till ready
  hosts: all
  pre_tasks:
    - name: Wait for connection
      ansible.builtin.wait_for_connection:
        # wait_for_connection_timeout host var should be increased for newly spawned cloud nodes.
        timeout: "{{ wait_for_connection_timeout | default(10) }}"

    - name: Check if we're on a cloud instance
      ansible.builtin.shell: command -v cloud-init >/dev/null 2>&1
      register: is_cloudinit_exist
      changed_when: false
      ignore_errors: true

    - name: Wait for cloud-init / user-data to finish
      ansible.builtin.command: cloud-init status --wait
      changed_when: false
      when: is_cloudinit_exist.rc == 0

- name: Foundation
  hosts: all
  roles:
    - role: all
    - role: userspace
      userspace_user: "{{ ansible_user }}"

- name: Canyon
  hosts: canyon.labnet
  roles:
    - role: unique_canyon
- name: Container
  hosts: container.labnet
  roles:
    - role: unique_container
- name: Laptop
  hosts: laptop.labnet
  roles:
    - role: unique_laptop
- name: Workstation
  hosts: workstation.labnet
  roles:
    - role: unique_workstation

- name: Step CA
  hosts: ca
  roles:
    - role: maxhoesel.smallstep.step_ca
      become: true
      vars:
        step_cli_version: 0.24.4
        step_ca_version: 0.25.2
        step_ca_name: Labnet CA
        step_ca_root_password: "{{ ca_root_password }}"
        step_ca_dns: "{{ inventory_hostname }}"
        step_ca_address: ":4431"
        step_ca_url: "https://{{ inventory_hostname }}:4431"

- name: Step CA Client
  hosts: all
  roles:
    - role: maxhoesel.smallstep.step_bootstrap_host
      when: "'ca' not in group_names"
      become: true
      vars:
        step_cli_version: 0.24.4
        step_bootstrap_ca_url: "https://workstation.{{ realm }}:4431"
        step_bootstrap_fingerprint: 20de2454dc737e3518ef6920d3224e36fecf1212ce8bbf3e46abdad1bb22189f

    - role: prometheus.prometheus.node_exporter
      node_exporter_enabled_collectors:
        - processes
        - systemd

- name: Artifact Stores
  hosts: artifactstores
  roles:
    - role: podman_nexus

- name: GPU Intel
  hosts: gpu_intel
  roles:
    - role: gpu_intel

- name: Desktops
  hosts: desktops
  roles:
    - role: desktop
- name: Hires Desktops
  hosts: hires_desktops
  roles:
    - role: desktop_hires

- name: Service Hosts
  hosts: servicehosts
  roles:
    - role: podman_host
    - role: podman_traefik
    - role: prometheus.prometheus.cadvisor

- name: DB Hosts
  hosts: dbhosts
  roles:
    - role: podman_postgres

- name: DNS Resolvers
  hosts: dnsresolvers
  roles:
    - role: podman_pihole

- name: Auth Servers
  hosts: authservers
  roles:
    - role: podman_keycloak
      vars:
        podman_keycloak_admin: "{{ keycloak_admin }}"
        podman_keycloak_admin_password: "{{ keycloak_admin_password }}"
    - role: podman_oauth2proxy

- name: GitLabs
  hosts: gitlabs
  roles:
    - role: podman_gitlab

- name: Media Servers
  hosts: mediaservers
  roles:
    - role: podman_jellyfin
    - role: podman_lidarr
    - role: podman_prowlarr
    - role: podman_qbittorrent
    - role: podman_radarr
    - role: podman_recyclarr
    - role: podman_sonarr
    # - role: podman_ytdlsub

- name: Metrics Collectors
  hosts: metricscollectors
  roles:
    - role: podman_prometheus

- name: Metrics Monitors
  hosts: metricsmonitors
  roles:
    - role: podman_grafana
