#!/usr/bin/env ansible-playbook

---
- name: Wait till ready
  hosts: all
  pre_tasks:
    - name: Wait for connection
      ansible.builtin.wait_for_connection:
        # wait_for_connection_timeout host var should be increased for newly spawned cloud nodes.
        timeout: "{{ wait_for_connection_timeout | default(10) }}"

    - name: Check if we're on a cloud instance
      ansible.builtin.shell: command -v cloud-init >/dev/null 2>&1
      register: is_cloudinit_exist
      changed_when: false
      ignore_errors: true

    - name: Wait for cloud-init / user-data to finish
      ansible.builtin.command: cloud-init status --wait
      changed_when: false
      when: is_cloudinit_exist.rc == 0

- name: Foundation
  hosts: all
  roles:
    - role: all
    - role: userspace
      userspace_user: "{{ ansible_user }}"

- name: Step CA
  hosts: ca
  roles:
    - role: maxhoesel.smallstep.step_ca
      become: true
      vars:
        step_cli_version: 0.24.4
        step_ca_version: 0.25.2
        step_ca_name: Labnet CA
        step_ca_root_password: "{{ ca_root_password }}"
        step_ca_dns: "{{ inventory_hostname }}"
        step_ca_address: ":4431"
        step_ca_url: "https://{{ inventory_hostname }}:4431"

- name: Step CA Client
  hosts: all
  roles:
    - role: maxhoesel.smallstep.step_bootstrap_host
      become: true
      vars:
        step_cli_version: 0.24.4
        step_bootstrap_ca_url: "https://container.{{ realm }}:4431"
        step_bootstrap_fingerprint: 0e6b5947ad1f7032b34ce7b8af22cc98445eef9c69a5f19832afefc726529cbc
        step_bootstrap_force: true

- name: Node Metrics Exporter
  hosts: servicehosts
  roles:
    - role: prometheus.prometheus.node_exporter
      node_exporter_enabled_collectors:
        - processes
        - systemd

- name: GPU Intel
  hosts: gpu_intel
  roles:
    - role: gpu_intel

- name: Desktops
  hosts: desktops
  roles:
    - role: desktop

- name: Apply roles
  import_playbook: roles.yml
