---
- name: Create groups
  become: true
  register: _groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
    system: true
  loop: "{{ qbittorrent_groups }}"

- name: Ensure {{ ansible_user }} is a group member
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ qbittorrent_groups }}"
    append: true

- name: Create user
  become: true
  register: _user
  ansible.builtin.user:
    comment: "{{ qbittorrent_name }}"
    create_home: false
    group: "{{ _groups.results[0].gid }}"
    groups: "{{ qbittorrent_groups }}"
    home: "{{ qbittorrent_basedir }}"
    name: "{{ qbittorrent_id }}"
    password: "!"
    shell: "/usr/sbin/nologin"
    system: true


- name: Ensure working directory exists
  become: true
  ansible.builtin.file:
    path: "{{ qbittorrent_basedir }}"
    state: directory
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"

- name: Ensure directories exist
  become: true
  ansible.builtin.file:
    path: "{{ qbittorrent_basedir }}/{{ item }}"
    state: directory
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"
  loop:
    - config
    - config/wireguard


- name: Copy wireguard configuration
  become: true
  ansible.builtin.template:
    src: wg0.conf.j2
    dest: "{{ qbittorrent_basedir }}/config/wireguard/wg0.conf"
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"
    mode: 0600


- name: Copy service files
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ directory_systemd }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - qbittorrent-exporter.service
    - qbittorrent-main.service
    - qbittorrent-wg.service
    - qbittorrent.service

- name: Enable and check service
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    name: qbittorrent
    state: restarted
