---
- name: Ensure working directories exist
  become: true
  ansible.builtin.file:
    path: "{{ postgres_basedir }}/{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
  loop:
    - data

- name: Copy service files
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ directory_systemd }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - postgres-exporter.service
    - postgres-main.service
    - postgres.service

- name: Enable and check Postgres service
  become: true
  ansible.builtin.systemd:
    name: postgres
    daemon_reload: true
    state: restarted
    enabled: true
