---
- name: Create groups
  become: true
  register: _groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
    system: true
  loop: "{{ postgres_groups }}"

- name: Ensure {{ ansible_user }} is a group member
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ postgres_groups }}"
    append: true

- name: Create user
  become: true
  register: _user
  ansible.builtin.user:
    comment: "{{ postgres_name }}"
    create_home: false
    group: "{{ _groups.results[0].gid }}"
    groups: "{{ postgres_groups }}"
    home: "{{ postgres_basedir }}"
    name: "{{ postgres_id }}"
    password: "!"
    shell: "/usr/sbin/nologin"
    system: true


- name: Ensure working directory exists
  become: true
  ansible.builtin.file:
    path: "{{ postgres_basedir }}"
    state: directory
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"

- name: Ensure directories exist
  become: true
  ansible.builtin.file:
    path: "{{ postgres_basedir }}/{{ item }}"
    state: directory
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"
  loop:
    - data


- name: Create secret postgres_master_password
  become: true
  containers.podman.podman_secret:
    data: "{{ postgres_master_password }}"
    force: true
    name: postgres_master_password
    state: present
- name: Create secret postgres_master_user
  become: true
  containers.podman.podman_secret:
    data: "{{ postgres_master_user }}"
    force: true
    name: postgres_master_user
    state: present


- name: Copy service files
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ directory_systemd }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - postgres-exporter.service
    - postgres-main.service
    - postgres.service

- name: Enable and check service
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    name: postgres
    state: restarted
