---
- name: Remove conflicting packages
  become: true
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Install dependencies
  become: true
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true

- name: Create keyring storage
  become: true
  file:
    path: "{{ directory_keyrings }}"
    state: directory
- name: Install APT key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    keyring: "{{ directory_keyrings }}/docker.gpg"
    state: present

- name: Add Docker Repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by={{ directory_keyrings }}/docker.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker
  become: true
  ansible.builtin.apt:
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Install docker python package
  become: true
  ansible.builtin.pip:
    name: docker

- name: Ensure /etc/docker exists
  become: true
  ansible.builtin.file:
    path: /etc/docker
    state: directory
- name: Enable IPv6 networking in Docker
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/etc/docker/daemon.json"
    dest: /etc/docker/daemon.json
    mode: 0644

- name: Add user '{{ ansible_user }}' to Docker group
  become: true
  ansible.builtin.user:
    name: '{{ ansible_user }}'
    groups: docker
    append: true

- name: Enable and check docker service
  become: true
  ansible.builtin.systemd:
    name: docker
    daemon_reload: true
    state: restarted
    enabled: true

- name: Enable and check systemd-networkd service
  become: true
  ansible.builtin.systemd:
    name: systemd-networkd
    daemon_reload: true
    state: started
    enabled: true

- name: Enable and check systemd-networkd-wait-online service
  become: true
  ansible.builtin.systemd:
    name: systemd-networkd-wait-online
    daemon_reload: true
    state: started
    enabled: true
