---
- name: Ensure working directory exists
  become: true
  ansible.builtin.file:
    path: "{{ oauth2proxy_basedir }}"
    state: directory
    owner: "{{ ansible_user }}"

- name: Ensure directories exists
  become: true
  ansible.builtin.file:
    path: "{{ oauth2proxy_basedir }}/templates"
    state: directory
    owner: "{{ ansible_user }}"

- name: Copy oauth2proxy service file
  become: true
  ansible.builtin.template:
    src: oauth2proxy.service.j2
    dest: "{{ directory_systemd }}/oauth2proxy.service"
    owner: root
    group: root
    mode: 0644

- name: Enable and check oauth2proxy service
  become: true
  ansible.builtin.systemd:
    name: oauth2proxy
    daemon_reload: true
    state: restarted
    enabled: true
