---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age19xq3hk7ylucjkrn3y83gzntr4e5agr2xka6y89aec5c474su5ggql973qy
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age19xq3hk7ylucjkrn3y83gzntr4e5agr2xka6y89aec5c474su5ggql973qy
