---
- name: Enable High-DPI display scaling
  hosts: desktop-hidpi
  
  tasks:
  #- name: Set DPI for X
  #  community.general.xfconf:
  #    channel: "xsettings"
  #    property: "/Xft/DPI"
  #    value_type: "int"
  #    value: "192"

  - name: Set window scaling factor
    community.general.xfconf:
      channel: "xsettings"
      property: "/Gdk/WindowScalingFactor"
      value_type: "int"
      value: "2"

  - name: Set window manager theme
    community.general.xfconf:
      channel: "xfwm4"
      property: "/general/theme"
      value_type: "string"
      value: "Default-xhdpi"