#!/usr/bin/env bash

# Initial entrypoint for Ansible managed node initialization

set -o errexit
set -o nounset
set -o pipefail
if [[ "${TRACE-0}" == "1" ]]; then
  set -o xtrace
fi

cd "$(dirname "$0")"

main() {
  SSH_KEY=${HOME}/.ssh/id_ed25519

  sudo apt-get update

  # Install Ansible

  sudo apt-get install --yes python3 python3-pip

  export PATH=${PATH}:${HOME}/.local/bin
  python3 -m pip install --user ansible

  # Prepare SSH

  sudo apt-get install --yes openssh-server

  echo ""
  echo Process completed.
  echo Use \'ssh-copy-id -i "${SSH_KEY}" "$(hostname -I | cut -d' ' -f1)"\' to copy your SSH key to this Ansible managed nodes.
}

main "$@"
