#!/usr/bin/env bash

# Initial entrypoint for Ansible control node initialization

set -o errexit
set -o nounset
set -o pipefail
if [[ "${TRACE-0}" == "1" ]]; then
  set -o xtrace
fi

cd "$(dirname "$0")"

main() {
  SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
  ANSIBLE_INVENTORY=${SCRIPT_DIR}/provision/ansible/inventory
  SSH_KEY=${HOME}/.ssh/id_ed25519

  sudo apt-get update

  # Install Ansible

  sudo apt-get install --yes python3 python3-pip

  export PATH=${PATH}:${HOME}/.local/bin
  python3 -m pip install --user ansible

  # Prepare SSH

  sudo apt-get install --yes openssh-client

  # Generate an SSH key if it doesn't exist
  if [[ ! -e $SSH_KEY ]]; then
    # ed25519 elliptic curve, with 100 rounds of key derivation, empty passphrase
    ssh-keygen -t ed25519 -a 100 -N '' -f "$SSH_KEY" <<<y
  else
    echo
    echo "NOTICE: Existing SSH key found at '${SSH_KEY}'! NOT replacing existing key."
  fi

  echo
  echo Process completed.
  echo Ansible inventory: "$ANSIBLE_INVENTORY"
  echo SSH key: "$SSH_KEY"
  echo Use \'ssh-copy-id -i "${SSH_KEY}" ...\' to copy this key to your Ansible managed nodes.
  echo Use Makefile targets to issue commands.
}

main "$@"
