#!/usr/bin/env bash

# Initial entrypoint for Ansible managed node initialization

set -o errexit
set -o nounset
set -o pipefail
if [[ "${TRACE-0}" == "1" ]]; then
  set -o xtrace
fi

cd "$(dirname "$0")"

main() {
  SSH_KEY=${HOME}/.ssh/id_ed25519

  sudo apt-get update

  # Install Ansible

  sudo apt-get install --yes python3 python3-pip pipx

  export PATH=${PATH}:${HOME}/.local/bin
  pipx install --include-deps ansible

    # Install SOPS

  wget https://github.com/getsops/sops/releases/download/v3.7.3/sops-v3.7.3.linux.amd64 \
    --output-document=${HOME}/.local/bin/sops
  chmod +x ${HOME}/.local/bin/sops

  # Prepare SSH

  sudo apt-get install --yes openssh-server

  echo ""
  echo Process completed.
  echo Use \'ssh-copy-id -i "${SSH_KEY}" "$(hostname -I | cut -d' ' -f1)"\' to copy your SSH key to this Ansible managed nodes.
}

main "$@"
