---
- name: Set window scaling factor
  community.general.xfconf:
    channel: "xsettings"
    property: "/Gdk/WindowScalingFactor"
    value_type: "int"
    value: "2"

- name: Set window manager theme
  community.general.xfconf:
    channel: "xfwm4"
    property: "/general/theme"
    value_type: "string"
    value: "Default-xhdpi"

- include_tasks: ./coding-environment.yml
- include_tasks: ./keepassxc.yml
- include_tasks: ./discord.yml
