---
- name: Create groups
  become: true
  register: _groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
    system: true
  loop: "{{ podman_traefik_groups }}"

- name: Ensure user is a group member
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ podman_traefik_groups }}"
    append: true

- name: Create user
  become: true
  register: _user
  ansible.builtin.user:
    comment: "{{ podman_traefik_name }}"
    create_home: false
    group: "{{ _groups.results[0].gid }}"
    groups: "{{ podman_traefik_groups }}"
    home: "{{ podman_traefik_basedir }}"
    name: "{{ podman_traefik_id }}"
    password: "!"
    shell: "/usr/sbin/nologin"
    system: true


- name: Ensure working directory exists
  become: true
  ansible.builtin.file:
    path: "{{ podman_traefik_basedir }}"
    state: directory
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"
    mode: "0o750"

- name: Ensure directories exist
  become: true
  ansible.builtin.file:
    path: "{{ podman_traefik_basedir }}/{{ item }}"
    state: directory
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"
    mode: "0o750"
  loop:
    - acme
    - conf.d


- name: Copy traefik config file
  become: true
  ansible.builtin.template:
    src: "traefik.yml.j2"
    dest: "{{ podman_traefik_basedir }}/traefik.yml"
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"
    mode: "0o640"

- name: Copy traefik dynamic config file
  become: true
  ansible.builtin.template:
    src: "traefik_dynamic_default.yml.j2"
    dest: "{{ podman_traefik_basedir }}/conf.d/traefik_dynamic_default.yml"
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"
    mode: "0o640"


- name: Pull service image
  become: true
  containers.podman.podman_image:
    name: "{{ registry_dockerio }}/library/traefik:{{ podman_traefik_version }}"

- name: Copy service files
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ directory_systemd }}/{{ item }}"
    owner: root
    group: root
    mode: "0o644"
  loop:
    - traefik.service

- name: Enable and check service
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    name: traefik
    state: restarted
