---
- name: Ensure working directory exists
  become: true
  ansible.builtin.file:
    path: "{{ podman_traefik_basedir }}"
    state: directory
    owner: root
    group: root
    mode: "u=rwX,g=,o="
    recurse: true
  notify: Restart traefik

- name: Ensure directories exist
  become: true
  ansible.builtin.file:
    path: "{{ podman_traefik_basedir }}/{{ item }}"
    state: directory
    owner: root
    group: root
    # acme.json must not be group-readable.
    # Might as well lock everything down.
    mode: "u=rwX,g=,o="
    recurse: true
  loop:
    - acme
    - conf.d
  notify: Restart traefik


- name: Copy traefik config file
  become: true
  ansible.builtin.template:
    src: "traefik.yml.j2"
    dest: "{{ podman_traefik_basedir }}/traefik.yml"
    owner: root
    group: root
    mode: "0o600"
  notify: Restart traefik

- name: Copy traefik dynamic config file
  become: true
  ansible.builtin.template:
    src: "traefik_dynamic_default.yml.j2"
    dest: "{{ podman_traefik_basedir }}/conf.d/traefik_dynamic_default.yml"
    owner: root
    group: root
    mode: "0o600"
  notify: Restart traefik


- name: Pull service image
  become: true
  register: result
  retries: 3
  delay: 3
  until: result is not failed
  containers.podman.podman_image:
    name: "docker.io/library/traefik:{{ podman_traefik_version }}"

- name: Copy service files
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ directory_systemd }}/{{ item }}"
    owner: root
    group: root
    mode: "0o644"
  loop:
    - traefik.service
  notify: Restart traefik

- name: Enable and check service
  become: true
  ansible.builtin.systemd:
    name: traefik
    enabled: true
  notify: Restart traefik
