---
- name: Install Intel driver
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
      - intel-gpu-tools
      - intel-media-va-driver-non-free
      - vainfo
      - vdpauinfo
