---
- name: Create groups
  become: true
  register: _podman_jellyfin_groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
    system: true
  loop: "{{ podman_jellyfin_groups }}"
  notify: Restart jellyfin

- name: Ensure user is a group member
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ podman_jellyfin_groups }}"
    append: true
  notify: Restart jellyfin

- name: Create user
  become: true
  register: _podman_jellyfin_user
  ansible.builtin.user:
    comment: "{{ podman_jellyfin_name }}"
    create_home: false
    group: "{{ _podman_jellyfin_groups.results[0].gid }}"
    groups: "{{ podman_jellyfin_groups }}"
    home: "{{ podman_jellyfin_basedir }}"
    name: "{{ podman_jellyfin_id }}"
    password: "!"
    shell: "/usr/sbin/nologin"
    system: true
  notify: Restart jellyfin


- name: Ensure working directory exists
  become: true
  ansible.builtin.file:
    path: "{{ podman_jellyfin_basedir }}"
    state: directory
    owner: "{{ _podman_jellyfin_user.uid }}"
    group: "{{ _podman_jellyfin_groups.results[0].gid }}"
    mode: "u=rwX,g=rX"
    recurse: true
  notify: Restart jellyfin

- name: Ensure directories exist
  become: true
  ansible.builtin.file:
    path: "{{ podman_jellyfin_basedir }}/{{ item }}"
    state: directory
    owner: "{{ _podman_jellyfin_user.uid }}"
    group: "{{ _podman_jellyfin_groups.results[0].gid }}"
    mode: "u=rwX,g=rX"
    recurse: true
  loop:
    - cache
    - config
  notify: Restart jellyfin

- name: Get groups
  ansible.builtin.getent:
    database: group

- name: Copy service files
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ directory_systemd }}/{{ item }}"
    owner: root
    group: root
    mode: "0o644"
  loop:
    - jellyfin.service
    - jellyfin.timer
  notify: Restart jellyfin

- name: Enable and check jellyfin service
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: jellyfin
  notify: Restart jellyfin
