---
- name: Set timezone
  become: true
  community.general.timezone:
    name: "{{ config_system_timezone }}"

- name: Configure locales to be generated
  become: true
  ansible.builtin.debconf:
    name: locales
    question: locales/locales_to_be_generated
    value: de_DE.UTF-8 UTF-8, en_US.UTF-8 UTF-8
    vtype: multiselect

- name: Reconfigure locales
  become: true
  ansible.builtin.command:
    cmd: "dpkg-reconfigure locales"
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Ensure default locales are available
  become: true
  community.general.locale_gen:
    name: "{{ item }}"
    state: present
  with_items:
    - de_DE
    - de_DE.UTF-8
    - en_US
    - en_US.UTF-8

- name: Define locale 'en_DE.UTF-8'
  become: true
  ansible.builtin.command:
    cmd: localedef -i de_DE -f UTF-8 en_DE.UTF-8

- name: Configure locale
  become: true
  ignore_errors: true
  ansible.builtin.command:
    cmd: localectl set-locale {{ config_system_locale }}
