---
- name: Set timezone
  become: true
  community.general.timezone:
    name: "{{ config_system_timezone }}"

- name: Ensure localisation files are available
  become: true
  community.general.locale_gen:
    name: "{{ config_system_locale }}"
    state: present

- name: Ensure localisation files are available
  become: true
  community.general.locale_gen:
    name: "{{ config_system_language }}"
    state: present
