---
- ansible.builtin.gather_facts:
- name: Set timezone to '{{ config_system_timezone }}'
  become: true
  community.general.timezone:
    name: "{{ config_system_timezone }}"

- name: Ensure localisation files for '{{ config_system_locale }}' are available
  become: true
  locale_gen:
    name: "{{ config_system_locale }}"
    state: present

- name: Ensure localisation files for '{{ config_system_language }}' are available
  become: true
  locale_gen:
    name: "{{ config_system_language }}"
    state: present
