---
- name: Generate SSH key
  become: true
  become_user: "{{ userspace_user }}"
  community.crypto.openssh_keypair:
    type: ed25519
    path: "/home/{{ userspace_user }}/.ssh/id_ed25519"
    force: false
    regenerate: never
    mode: "0o600"
    owner: "{{ userspace_user }}"

- name: Add user to systemd-journal group
  become: true
  ansible.builtin.user:
    name: "{{ userspace_user }}"
    groups: systemd-journal
    append: true

- name: Copy .bashrc
  become: true
  become_user: "{{ userspace_user }}"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/home/.bashrc"
    dest: "/home/{{ userspace_user }}/.bashrc"
    owner: "{{ userspace_user }}"
    mode: "0o600"
- name: Copy .profile
  become: true
  become_user: "{{ userspace_user }}"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/home/.profile"
    dest: "/home/{{ userspace_user }}/.profile"
    owner: "{{ userspace_user }}"
    mode: "0o600"

- name: "Ensure default config directory exists: htop"
  become: true
  become_user: "{{ userspace_user }}"
  ansible.builtin.file:
    path: "/home/{{ userspace_user }}/.config/htop"
    state: directory
    owner: "{{ userspace_user }}"
    mode: "u=rwX,g=rX"
    recurse: true
- name: "Install default configs: htop"
  become: true
  become_user: "{{ userspace_user }}"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/home/.config/htop/htoprc"
    dest: "/home/{{ userspace_user }}/.config/htop/htoprc"
    owner: "{{ userspace_user }}"
    mode: "0o600"

- name: Ensure working directory exists
  become: true
  ansible.builtin.file:
    path: "{{ userspace_downloads }}"
    state: directory
    owner: "{{ userspace_user }}"
    mode: "u=rwX,g=rX"
    recurse: true

- name: Download Oh My Zsh installer
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: "{{ userspace_downloads }}/install-ohmyzsh.sh"
    mode: "0o750"
- name: Execute the installer
  become: true
  become_user: "{{ userspace_user }}"
  ansible.builtin.command:
    cmd: "{{ userspace_downloads }}/install-ohmyzsh.sh --unattended"
    creates: "/home/{{ userspace_user }}/.oh-my-zsh"
- name: Install Powerlevel10k theme
  become: true
  become_user: "{{ userspace_user }}"
  ansible.builtin.git:
    repo: "https://github.com/romkatv/powerlevel10k.git"
    dest: "/home/{{ userspace_user }}/.oh-my-zsh/themes/powerlevel10k"
    depth: 1
    version: bde5ca4c2aa6e0c52dd7f15cf216dffdb1ec788c

- name: Install ZSH auto-suggestions plugin
  become: true
  become_user: "{{ userspace_user }}"
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "/home/{{ userspace_user }}/.oh-my-zsh/plugins/zsh-autosuggestions"
    depth: 1
    version: c3d4e576c9c86eac62884bd47c01f6faed043fc5
- name: Install ZSH syntax highlighting plugin
  become: true
  become_user: "{{ userspace_user }}"
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "/home/{{ userspace_user }}/.oh-my-zsh/plugins/zsh-syntax-highlighting"
    depth: 1
    version: e0165eaa730dd0fa321a6a6de74f092fe87630b0
- name: Install .zshrc
  become: true
  become_user: "{{ userspace_user }}"
  ansible.builtin.template:
    src: home/.zshrc.j2
    dest: "/home/{{ userspace_user }}/.zshrc"
    owner: "{{ userspace_user }}"
    mode: "0o600"

- name: Install powerlevel10k config
  become: true
  become_user: "{{ userspace_user }}"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/home/.p10k.zsh"
    dest: "/home/{{ userspace_user }}/.p10k.zsh"
    owner: "{{ userspace_user }}"
    mode: "0o600"

- name: Set login shell
  become: true
  ansible.builtin.user:
    name: "{{ userspace_user }}"
    shell: /bin/zsh

- name: Install Meslo Nerd Font patched for Powerlevel10k
  become: true
  become_user: "{{ userspace_user }}"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/home/.local/share/fonts"
    dest: "/home/{{ userspace_user }}/.local/share/fonts"
    mode: "0o644"
    owner: "{{ userspace_user }}"

- name: Coding Environment
  ansible.builtin.include_tasks: coding-environment.yml
- name: Localization
  ansible.builtin.include_tasks: l10n.yml
- name: NodeJS
  ansible.builtin.include_tasks: nodejs.yml
