---
- name: Gather facts
  ansible.builtin.gather_facts:

- name: Generate SSH key
  community.crypto.openssh_keypair:
    type: ed25519
    path: "{{ userspace_user }}/.ssh/id_ed25519"
    force: false
    regenerate: never
    mode: 0600
    owner: "{{ userspace_user }}"

- name: Add user '{{ userspace_user }}' to systemd-journal group
  become: true
  ansible.builtin.user:
    name: "{{ userspace_user }}"
    groups: systemd-journal
    append: yes

- name: Copy .bashrc
  ansible.builtin.copy:
    src: "{{ role_path }}/files/home/.bashrc"
    dest: "{{ userspace_user }}/.bashrc"
- name: Copy .profile
  ansible.builtin.copy:
    src: "{{ role_path }}/files/home/.profile"
    dest: "{{ userspace_user}}/.profile"

- name: "Ensure default config directory exists: htop"
  file: 
    path: "{{ userspace_user }}/.config/htop"
    state: directory
- name: "Install default configs: htop"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/home/.config/htop/htoprc"
    dest: "{{ userspace_user }}/.config/htop/htoprc"

- name: Ensure working directory exists
  ansible.builtin.file:
    path: "{{ userspace_downloads }}"
    state: directory
    owner: "{{ userspace_user }}"

- name: Download Oh My Zsh installer
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: "{{ userspace_downloads }}/install-ohmyzsh.sh"
    mode: 0744
- name: Execute the installer
  ansible.builtin.shell: 
    cmd: "{{ userspace_downloads }}/install-ohmyzsh.sh --unattended"
    creates: "{{ userspace_user }}/.oh-my-zsh"
- name: Install Powerlevel10k theme
  ansible.builtin.git:
    repo: "https://github.com/romkatv/powerlevel10k.git"
    dest: "{{ userspace_user }}/.oh-my-zsh/themes/powerlevel10k"
    depth: 1
- name: Install ZSH auto-suggestions plugin
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "{{ userspace_user }}/.oh-my-zsh/plugins/zsh-autosuggestions"
    depth: 1
- name: Install ZSH syntax highlighting plugin
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "{{ userspace_user }}/.oh-my-zsh/plugins/zsh-syntax-highlighting"
    depth: 1
- name: Install .zshrc
  ansible.builtin.template:
    src: home/.zshrc.j2
    dest: "{{ userspace_user }}/.zshrc"
    mode: 0600
    
- name: Install powerlevel10k config
  ansible.builtin.copy:
    src: "{{ role_path }}/files/home/.p10k.zsh"
    dest: "{{ userspace_user }}/.p10k.zsh"

- name: Set login shell
  become: true
  ansible.builtin.user:
    name: "{{ userspace_user }}"
    shell: /bin/zsh

- name: Install Meslo Nerd Font patched for Powerlevel10k
  ansible.builtin.copy:
    src: "{{ role_path }}/files/home/.local/share/fonts"
    dest: "{{ userspace_user }}/.local/share/fonts"
    mode: 0644

- include_tasks: coding-environment.yml
- include_tasks: keyboard.yml
- include_tasks: l10n.yml
- include_tasks: nodejs.yml
