---
- name: Create groups
  become: true
  register: _groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
    system: true
  loop: "{{ jellyfin_groups }}"

- name: Ensure {{ ansible_user }} is a group member
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ jellyfin_groups }}"
    append: true

- name: Create user
  become: true
  register: _user
  ansible.builtin.user:
    comment: "{{ jellyfin_name }}"
    create_home: false
    group: "{{ _groups.results[0].gid }}"
    groups: "{{ jellyfin_groups }}"
    home: "{{ jellyfin_basedir }}"
    name: "{{ jellyfin_id }}"
    password: "!"
    shell: "/usr/sbin/nologin"
    system: true


- name: Ensure working directory exists
  become: true
  ansible.builtin.file:
    path: "{{ jellyfin_basedir }}"
    state: directory
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"

- name: Ensure directories exist
  become: true
  ansible.builtin.file:
    path: "{{ jellyfin_basedir }}/{{ item }}"
    state: directory
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"
  loop:
    - cache
    - config


- name: Copy service files
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ directory_systemd }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - jellyfin.service
    - jellyfin.timer

- name: Enable and check service
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    name: jellyfin
    state: restarted
