---
- name: Get render group
  ansible.builtin.getent:
    database: group
    key: render

- name: Copy Jellyfin service file
  become: true
  ansible.builtin.template:
    src: "jellyfin.service.j2"
    dest: "{{ directory_systemd }}/jellyfin.service"
    owner: root
    group: root
    mode: 0644

- name: Copy Jellyfin timer file
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/etc/systemd/jellyfin.timer"
    dest: "{{ directory_systemd }}/jellyfin.timer"
    mode: 0644

- name: Enable and check Jellyfin service
  become: true
  ansible.builtin.systemd:
    name: jellyfin
    daemon_reload: true
    state: restarted
    enabled: true
