roles:
  - src: gantsign.keyboard
    version: 1.5.0
  - src: gantsign.visual-studio-code
    version: 7.0.0

collections:
  - name: community.crypto
    version: 2.22.1
  - name: community.docker
    version: 3.12.2
  - name: community.general
    version: 9.4.0
  - name: community.postgresql
    version: 3.6.1
  - name: community.sops
    version: 1.9.1
  - name: containers.podman
    version: 1.16.1
  - name: maxhoesel.smallstep
    version: 0.24.5
  - name: prometheus.prometheus
    version: 0.19.0
