---
podman_nzbget_id: nzbget
podman_nzbget_name: NZBget
podman_nzbget_groups:
  - nas
  - service

podman_nzbget_username: nzbget
podman_nzbget_password: nzbget
podman_nzbget_basedir: /mnt/usb/nzbget
podman_nzbget_mediadir: /mnt/media
podman_nzbget_version: latest
podman_nzbget_servers:
  - name: invalid
    host: invalid
    username: invalid
    password: invalid
    active: yes
    level: 0
    encryption: yes
    port: 563
    connections: 8
    optional: no
