---
- name: Create groups
  become: true
  register: _groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
    system: true
  loop: "{{ lidarr_groups }}"

- name: Ensure {{ ansible_user }} is a group member
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ lidarr_groups }}"
    append: true

- name: Create user
  become: true
  register: _user
  ansible.builtin.user:
    comment: "{{ lidarr_name }}"
    create_home: false
    group: "{{ _groups.results[0].gid }}"
    groups: "{{ lidarr_groups }}"
    home: "{{ lidarr_basedir }}"
    name: "{{ lidarr_id }}"
    password: "!"
    shell: "/usr/sbin/nologin"
    system: true


- name: Ensure working directory exists
  become: true
  ansible.builtin.file:
    path: "{{ lidarr_basedir }}"
    state: directory
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"

- name: Ensure directories exist
  become: true
  ansible.builtin.file:
    path: "{{ lidarr_basedir }}/{{ item }}"
    state: directory
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"
  loop:
    - config


- name: Create postgres user
  community.postgresql.postgresql_user:
    host: localhost
    login_password: "{{ postgres_master_password }}"
    login_user: "{{ postgres_master_user }}"
    name: "{{ lidarr_pg_user }}"
    password: "{{ lidarr_pg_password }}"

- name: Create postgres database
  community.postgresql.postgresql_db:
    host: localhost
    login_password: "{{ postgres_master_password }}"
    login_user: "{{ postgres_master_user }}"
    name: "{{ lidarr_pg_db }}-{{ item }}"
    owner: "{{ lidarr_pg_user }}"
  loop:
    - main
    - log

- name: "GRANT ALL PRIVILEGES ON DATABASE 'db' TO 'user'"
  community.postgresql.postgresql_privs:
    host: localhost
    login_password: "{{ postgres_master_password }}"
    login_user: "{{ postgres_master_user }}"
    db: postgres
    privs: ALL
    type: database
    obj: "{{ lidarr_pg_db }}-{{ item }}"
    role: "{{ lidarr_pg_user }}"
  loop:
    - main
    - log

- name: "GRANT USAGE, CREATE ON SCHEMA PUBLIC TO 'user'"
  community.postgresql.postgresql_privs:
    host: localhost
    login_password: "{{ postgres_master_password }}"
    login_user: "{{ postgres_master_user }}"
    db: postgres
    privs: CREATE
    type: schema
    obj: public
    role: "{{ lidarr_pg_user }}"


- name: Copy configuration
  become: true
  ansible.builtin.template:
    src: "config.xml.j2"
    dest: "{{ lidarr_basedir }}/config/config.xml"
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"
    mode: 0644


- name: Copy service files
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ directory_systemd }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - lidarr-exporter.service
    - lidarr-main.service
    - lidarr.service

- name: Enable and check service
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    name: lidarr
    state: restarted
