---
- name: Install podman
  become: true
  ansible.builtin.apt:
    name: podman

- name: Create quadlet for network 'service'
  become: true
  containers.podman.podman_network:
    driver: bridge
    internal: false
    ip_range: "{{ podman_service_network_subnet | ansible.utils.ipmath(10) }}-{{ podman_service_network_subnet | ansible.utils.ipmath(254) }}"
    name: service.{{ inventory_hostname }}
    quadlet_options:
      - PodmanArgs=--interface-name=service0
      - Options=isolate=true
    state: quadlet
    subnet: "{{ podman_service_network_subnet }}"

- name: Create quadlet for network 'proton'
  become: true
  when: podman_proton_network_subnet is defined
  containers.podman.podman_network:
    driver: bridge
    internal: false
    ipv6: false
    name: proton.{{ inventory_hostname }}
    quadlet_options:
      - PodmanArgs=--interface-name=proton0
      - Options=isolate=true
    state: quadlet
    subnet: "{{ podman_proton_network_subnet }}"
