---
- name: Install podman
  become: true
  ansible.builtin.apt:
    name: podman

- name: Create quadlet for network service
  become: true
  containers.podman.podman_network:
    internal: false
    ipv6: false
    name: service.{{ inventory_hostname }}
    opt:
      isolate: true
    state: quadlet
    subnet: "{{ podman_service_network_subnet }}"

- name: Create quadlet for network proton
  become: true
  when: podman_proton_network_subnet is defined
  containers.podman.podman_network:
    internal: false
    ipv6: false
    name: proton.{{ inventory_hostname }}
    opt:
      isolate: true
    state: quadlet
    subnet: "{{ podman_proton_network_subnet }}"
