---
- name: Install commonly used dependencies
  become: true
  register: result
  retries: 3
  delay: 3
  until: result is not failed
  ansible.builtin.apt:
    name:
      - wpasupplicant
    update_cache: true

- name: Set hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Configure podman
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/etc/containers/containers.conf"
    dest: /etc/containers/containers.conf
    owner: root
    group: root
    mode: "0o644"

- name: "Create network: labnet"
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/etc/systemd/network/labnet.network"
    dest: "{{ directory_networkd }}/labnet.network"
    owner: root
    group: root
    mode: "0o644"
  notify: Restart systemd-networkd

- name: "Create network: offline"
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/etc/systemd/network/offline.network"
    dest: "{{ directory_networkd }}/offline.network"
    owner: root
    group: root
    mode: "0o644"
  notify: Restart systemd-networkd

- name: Install wpasupplicant
  become: true
  register: result
  retries: 3
  delay: 3
  until: result is not failed
  ansible.builtin.apt:
    name:
      - wpasupplicant
    update_cache: true
  notify: Restart systemd-networkd

- name: "Store WPA config: offline"
  become: true
  ansible.builtin.template:
    src: wpa_supplicant-wlp2s0.conf.j2
    dest: /etc/wpa_supplicant/wpa_supplicant-wlp2s0.conf
    owner: root
    group: root
    mode: "0o600"
  notify: Restart systemd-networkd

- name: Configure DNS
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/etc/systemd/resolved.conf"
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root
    mode: "0o644"
  notify: Restart systemd-resolved

- name: Create storage mounts
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/etc/systemd/{{ item }}"
    dest: "{{ directory_systemd }}/{{ item }}"
    mode: "0o644"
    owner: root
    group: root
  loop:
    - mnt-usb.automount
    - mnt-usb.mount
  notify: Reload systemd

- name: Configure USB mount
  become: true
  ansible.builtin.systemd:
    enabled: false
    name: mnt-usb.mount
    state: started
  notify: Reload systemd

- name: Configure USB automount
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: mnt-usb.automount
  notify: Reload systemd
