---
- name: Create groups
  become: true
  register: _groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
    system: true
  loop: "{{ prowlarr_groups }}"

- name: Ensure {{ ansible_user }} is a group member
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ prowlarr_groups }}"
    append: true

- name: Create user
  become: true
  register: _user
  ansible.builtin.user:
    comment: "{{ prowlarr_name }}"
    create_home: false
    group: "{{ _groups.results[0].gid }}"
    groups: "{{ prowlarr_groups }}"
    home: "{{ prowlarr_basedir }}"
    name: "{{ prowlarr_id }}"
    password: "!"
    shell: "/usr/sbin/nologin"
    system: true


- name: Ensure working directory exists
  become: true
  ansible.builtin.file:
    path: "{{ prowlarr_basedir }}"
    state: directory
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"

- name: Ensure directories exist
  become: true
  ansible.builtin.file:
    path: "{{ prowlarr_basedir }}/{{ item }}"
    state: directory
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"
  loop:
    - config


- name: Copy configuration
  become: true
  ansible.builtin.template:
    src: config.xml.j2
    dest: "{{ prowlarr_basedir }}/config/config.xml"
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"
    mode: 0644


- name: Copy service files
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ directory_systemd }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - prowlarr-exporter.service
    - prowlarr-flaresolverr.service
    - prowlarr-main.service
    - prowlarr.service

- name: Enable and check prowlarr service
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    name: prowlarr
    state: restarted
