---
- name: Ensure working directory exists
  become: true
  ansible.builtin.file:
    path: "{{ prowlarr_basedir }}"
    state: directory
    owner: "{{ ansible_user }}"

- name: Ensure config directory exists
  become: true
  ansible.builtin.file:
    path: "{{ prowlarr_basedir }}/config"
    state: directory
    owner: "{{ ansible_user }}"

- name: Copy wireguard configuration
  become: true
  ansible.builtin.template:
    src: wg0.conf.j2
    dest: "{{ prowlarr_basedir }}/config/wireguard/wg0.conf"
    owner: root
    group: root
    mode: 0600

- name: Copy prowlarr service file
  become: true
  ansible.builtin.template:
    src: prowlarr.service.j2
    dest: "{{ directory_systemd }}/prowlarr.service"
    owner: root
    group: root
    mode: 0644

- name: Enable and check prowlarr service
  become: true
  ansible.builtin.systemd:
    name: prowlarr
    daemon_reload: true
    state: restarted
    enabled: true
