---
- name: Ensure working directories exist
  become: true
  ansible.builtin.file:
    path: "{{ prowlarr_basedir }}/{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
  loop:
    - config

- name: Copy configuration
  become: true
  ansible.builtin.template:
    src: "config.xml.j2"
    dest: "{{ prowlarr_basedir }}/config/config.xml"
    owner: 1001
    group: 1001
    mode: 0644

- name: Copy service files
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ directory_systemd }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - prowlarr-exporter.service
    - prowlarr-flaresolverr.service
    - prowlarr-main.service
    - prowlarr.service

- name: Enable and check prowlarr service
  become: true
  ansible.builtin.systemd:
    name: prowlarr
    daemon_reload: true
    state: restarted
    enabled: true
