---
- name: Create groups
  become: true
  register: _podman_lidarr_groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
    system: true
  loop: "{{ podman_lidarr_groups }}"
  notify: Restart lidarr

- name: Ensure user is a group member
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ podman_lidarr_groups }}"
    append: true
  notify: Restart lidarr

- name: Create user
  become: true
  register: _podman_lidarr_user
  ansible.builtin.user:
    comment: "{{ podman_lidarr_name }}"
    create_home: false
    group: "{{ _podman_lidarr_groups.results[0].gid }}"
    groups: "{{ podman_lidarr_groups }}"
    home: "{{ podman_lidarr_basedir }}"
    name: "{{ podman_lidarr_id }}"
    password: "!"
    shell: "/usr/sbin/nologin"
    system: true
  notify: Restart lidarr


- name: Ensure working directory exists
  become: true
  ansible.builtin.file:
    path: "{{ podman_lidarr_basedir }}"
    state: directory
    owner: "{{ _podman_lidarr_user.uid }}"
    group: "{{ _podman_lidarr_groups.results[0].gid }}"
    mode: "u=rwX,g=rX,o="
    recurse: false
  notify: Restart lidarr

- name: Ensure directories exist
  become: true
  ansible.builtin.file:
    path: "{{ podman_lidarr_basedir }}/{{ item }}"
    state: directory
    owner: "{{ _podman_lidarr_user.uid }}"
    group: "{{ _podman_lidarr_groups.results[0].gid }}"
    mode: "u=rwX,g=rX,o="
    recurse: true
  loop:
    - config
  notify: Restart lidarr


- name: Create postgres user
  register: podman_lidarr_result
  retries: 3
  delay: 3
  until: podman_lidarr_result is not failed
  community.postgresql.postgresql_user:
    host: localhost
    login_password: "{{ podman_postgres_master_password }}"
    login_user: "{{ podman_postgres_master_user }}"
    name: "{{ podman_lidarr_pg_user }}"
    password: "{{ podman_lidarr_pg_password }}"
  notify: Restart lidarr

- name: Create postgres database
  register: podman_lidarr_result
  retries: 3
  delay: 3
  until: podman_lidarr_result is not failed
  community.postgresql.postgresql_db:
    host: localhost
    login_password: "{{ podman_postgres_master_password }}"
    login_user: "{{ podman_postgres_master_user }}"
    name: "{{ podman_lidarr_pg_db }}-{{ item }}"
    owner: "{{ podman_lidarr_pg_user }}"
  loop:
    - main
    - log
  notify: Restart lidarr

- name: "GRANT ALL PRIVILEGES ON DATABASE 'db' TO 'user'"
  community.postgresql.postgresql_privs:
    host: localhost
    login_password: "{{ podman_postgres_master_password }}"
    login_user: "{{ podman_postgres_master_user }}"
    db: postgres
    privs: ALL
    type: database
    obj: "{{ podman_lidarr_pg_db }}-{{ item }}"
    role: "{{ podman_lidarr_pg_user }}"
  loop:
    - main
    - log
  notify: Restart lidarr

- name: "GRANT USAGE, CREATE ON SCHEMA PUBLIC TO 'user'"
  community.postgresql.postgresql_privs:
    host: localhost
    login_password: "{{ podman_postgres_master_password }}"
    login_user: "{{ podman_postgres_master_user }}"
    db: postgres
    privs: CREATE
    type: schema
    obj: public
    role: "{{ podman_lidarr_pg_user }}"
  notify: Restart lidarr


- name: Copy configuration
  become: true
  ansible.builtin.template:
    src: "config.xml.j2"
    dest: "{{ podman_lidarr_basedir }}/config/config.xml"
    owner: "{{ _podman_lidarr_user.uid }}"
    group: "{{ _podman_lidarr_groups.results[0].gid }}"
    mode: "0o640"
  notify: Restart lidarr


- name: Copy service files
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ directory_systemd }}/{{ item }}"
    owner: root
    group: root
    mode: "0o644"
  loop:
    - lidarr-exporter.service
    - lidarr-main.service
    - lidarr.service
  notify: Restart lidarr

- name: Enable and check lidarr service
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: lidarr
  notify: Restart lidarr
