---
- name: Create groups
  become: true
  register: _podman_mattermost_groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
    system: true
  loop: "{{ podman_mattermost_groups }}"

- name: Ensure user is a group member
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ podman_mattermost_groups }}"
    append: true

- name: Create user
  become: true
  register: _podman_mattermost_user
  ansible.builtin.user:
    comment: "{{ podman_mattermost_name }}"
    create_home: false
    group: "{{ _podman_mattermost_groups.results[0].gid }}"
    groups: "{{ podman_mattermost_groups }}"
    home: "{{ podman_mattermost_basedir }}"
    name: "{{ podman_mattermost_id }}"
    password: "!"
    shell: "/usr/sbin/nologin"
    system: true


- name: Ensure working directory exists
  become: true
  ansible.builtin.file:
    path: "{{ podman_mattermost_basedir }}"
    state: directory
    owner: "{{ _podman_mattermost_user.uid }}"
    group: "{{ _podman_mattermost_groups.results[0].gid }}"
    mode: "u=rwX,g=rX"
    recurse: true

- name: Ensure directories exist
  become: true
  ansible.builtin.file:
    path: "{{ podman_mattermost_basedir }}/{{ item }}"
    state: directory
    owner: "{{ _podman_mattermost_user.uid }}"
    group: "{{ _podman_mattermost_groups.results[0].gid }}"
    mode: "u=rwX,g=rX"
    recurse: true
  loop:
    - config
    - data
    - logs
    - plugins
    - client/plugins
    - bleve-indexes


- name: Create postgres user
  register: podman_mattermost_result
  retries: 3
  delay: 3
  until: podman_mattermost_result is not failed
  community.postgresql.postgresql_user:
    host: localhost
    login_password: "{{ podman_postgres_master_password }}"
    login_user: "{{ podman_postgres_master_user }}"
    name: "{{ podman_mattermost_pg_user }}"
    password: "{{ podman_mattermost_pg_password }}"

- name: Create postgres database
  register: podman_mattermost_result
  retries: 3
  delay: 3
  until: podman_mattermost_result is not failed
  community.postgresql.postgresql_db:
    host: localhost
    login_password: "{{ podman_postgres_master_password }}"
    login_user: "{{ podman_postgres_master_user }}"
    name: "{{ podman_mattermost_pg_db }}"
    owner: "{{ podman_mattermost_pg_user }}"

- name: "GRANT ALL PRIVILEGES ON DATABASE 'db' TO 'user'"
  community.postgresql.postgresql_privs:
    host: localhost
    login_password: "{{ podman_postgres_master_password }}"
    login_user: "{{ podman_postgres_master_user }}"
    db: postgres
    privs: ALL
    type: database
    obj: "{{ podman_mattermost_pg_db }}"
    role: "{{ podman_mattermost_pg_user }}"

- name: "GRANT USAGE, CREATE ON SCHEMA PUBLIC TO 'user'"
  community.postgresql.postgresql_privs:
    host: localhost
    login_password: "{{ podman_postgres_master_password }}"
    login_user: "{{ podman_postgres_master_user }}"
    db: postgres
    privs: CREATE
    type: schema
    obj: public
    role: "{{ podman_mattermost_pg_user }}"


- name: Copy service files
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ directory_systemd }}/{{ item }}"
    owner: root
    group: root
    mode: "0o644"
  loop:
    - mattermost.service

- name: Enable and check mattermost service
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    name: mattermost
    state: restarted
