#!/usr/bin/env ansible-playbook

---
- name: Wait till ready
  hosts: all
  pre_tasks:
    - name: Wait for connection
      ansible.builtin.wait_for_connection:
        # wait_for_connection_timeout host var should be increased for newly spawned cloud nodes.
        timeout: "{{ wait_for_connection_timeout | default(10) }}"

    - name: Check if we're on a cloud instance
      shell: command -v cloud-init >/dev/null 2>&1
      register: is_cloudinit_exist
      ignore_errors: true

    - name: Wait for cloud-init / user-data to finish
      command: cloud-init status --wait
      changed_when: false
      when: is_cloudinit_exist.rc == 0

- hosts: all
  roles:
    - role: all
    - role: userspace
      userspace_user: "{{ ansible_user }}"
