---
- hosts: "{{ target_host | default('laptop') }}"
  roles:
    - role: maxhoesel.smallstep.step_bootstrap_host
      vars:
        step_cli_version: 0.24.4
        step_bootstrap_ca_url: https://workstation.labnet:4431
        step_bootstrap_fingerprint: 20de2454dc737e3518ef6920d3224e36fecf1212ce8bbf3e46abdad1bb22189f
      become: true
    - role: unique-laptop
    - role: desktop
