---
- hosts: "{{ target_host | default('canyon') }}"
  gather_facts: false
  roles:
    - role: unique-canyon
    - role: gpu-intel
    - role: desktop
    - role: podman-docker-io
    - role: podman-jellyfin
      jellyfin_basedir: /home/oliver/jellyfin
    - role: podman-pihole
      pihole_basedir: /home/oliver/pihole
    