---
- hosts: "{{ target_host | default('canyon') }}"
  gather_subset:
    - "architecture"
    - "mounts"
  roles:
    - role: maxhoesel.smallstep.step_bootstrap_host
      vars:
        step_cli_version: 0.24.4
        step_bootstrap_ca_url: https://workstation.labnet:4431
        step_bootstrap_fingerprint: 20de2454dc737e3518ef6920d3224e36fecf1212ce8bbf3e46abdad1bb22189f
      become: true
    - role: unique-canyon
    - role: gpu-intel
    - role: desktop
    - role: prometheus.prometheus.node_exporter
      node_exporter_enabled_collectors:
        - processes
        - systemd
    - role: prometheus.prometheus.cadvisor
    # Required for roles below. Process first.
    - role: podman-host
    - role: podman-postgres
    - role: podman-prometheus
    # Application roles. Eventually consistent.
    - role: podman-bazarr
    - role: podman-grafana
    - role: podman-jellyfin
    - role: podman-keycloak
    - role: podman-lidarr
    - role: podman-mattermost
    - role: podman-oauth2proxy
    - role: podman-pihole
    - role: podman-prowlarr
    - role: podman-qbittorrent
    - role: podman-radarr
    - role: podman-sonarr
    - role: podman-synapse
    - role: podman-traefik
