---
- hosts: "{{ target_host | default('sandbox') }}"
  gather_facts: false
  roles:
    - role: certbot
    - role: podman-docker-io
    - role: podman-postgres
    - role: podman-lemmy
    - role: podman-lemmy-ui
