---
- hosts: "{{ target_host | default('workstation') }}"
  gather_facts: false
  roles:
    - role: unique-workstation
    - role: gpu-nvidia
    - role: docker-host
    - role: desktop
    - role: desktop-hires
