---
- hosts: "{{ target_host | default('workstation') }}"
  gather_subset:
    - "distribution_release"
    - "mounts"
  roles:
    - role: unique-workstation
    - role: desktop
    - role: desktop-hires
    - role: prometheus.prometheus.node_exporter
      node_exporter_enabled_collectors:
        - processes
        - systemd
    - role: prometheus.prometheus.cadvisor
    - role: userspace
      userspace_user: adesso-os
    # Required for roles below. Process first.
    - role: podman-host
    - role: podman-postgres
    # Application roles. Eventually consistent.
    - role: podman-grafana
    - role: podman-traefik
