---
- hosts: "{{ target_host | default('container') }}"
  gather_facts: true
  roles:
    - role: unique-container
    - role: gpu-intel
    - role: podman-postgres
    - role: podman-jellyfin
    - role: podman-pihole
    