---
- hosts: "{{ target_host | default('container') }}"
  gather_facts: false
  roles:
    - role: unique-container
    - role: gpu-intel
    - role: podman-docker-io
    - role: podman-jellyfin
    - role: podman-pihole
    