---
- hosts: "{{ target_host | default('workstation') }}"
  gather_facts: false
  roles:
    - role: unique-workstation
    - role: desktop
    - role: desktop-hires
    - role: userspace
      userspace_user: adesso-os
