---
- name: Create groups
  become: true
  register: _groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
    system: true
  loop: "{{ grafana_groups }}"

- name: Ensure {{ ansible_user }} is a group member
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ grafana_groups }}"
    append: true

- name: Create user
  become: true
  register: _user
  ansible.builtin.user:
    name: "{{ grafana_id }}"
    comment: "{{ grafana_name }}"
    group: "{{ _groups.results[0].gid }}"
    groups: "{{ grafana_groups }}"
    system: true

- name: Ensure working directory exists
  become: true
  ansible.builtin.file:
    path: "{{ grafana_basedir }}"
    state: directory
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"

- name: Ensure directories exists
  become: true
  ansible.builtin.file:
    path: "{{ grafana_basedir }}/{{ item }}"
    state: directory
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"
  loop:
    - data

- name: Copy service file
  become: true
  ansible.builtin.template:
    src: grafana.service.j2
    dest: "{{ directory_systemd }}/grafana.service"
    owner: root
    group: root
    mode: 0644

- name: Enable and check service
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    name: grafana
    state: restarted
