---
- name: Check APT non-free
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      apt-cache policy | grep bookworm/non-free
    executable: /bin/bash
  register: result_check_nonfree
  changed_when: result_check_nonfree.rc == 1
  failed_when: result_check_nonfree.rc > 1
- name: Enable APT non-free
  become: true
  ansible.builtin.command: apt-add-repository --yes non-free
  when: result_check_nonfree.rc == 1
  changed_when: true

- name: Check APT non-free-firmware
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      apt-cache policy | grep bookworm/non-free-firmware
    executable: /bin/bash
  register: result_check_nonfreefirmware
  changed_when: result_check_nonfreefirmware.rc == 1
  failed_when: result_check_nonfreefirmware.rc > 1
- name: Enable APT non-free-firmware
  become: true
  ansible.builtin.command: apt-add-repository --yes non-free-firmware
  when: result_check_nonfree.rc == 1
  changed_when: true

- name: Check APT contrib
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      apt-cache policy | grep bookworm/contrib
    executable: /bin/bash
  register: result_check_contrib
  changed_when: result_check_contrib.rc == 1
  failed_when: result_check_contrib.rc > 1
- name: Enable APT contrib
  become: true
  ansible.builtin.command: apt-add-repository --yes contrib
  when: result_check_contrib.rc == 1
  changed_when: true

- name: Check APT i386
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      dpkg --print-foreign-architectures | grep i386
    executable: /bin/bash
  register: result_i386_check
  changed_when: result_i386_check.rc == 1
  failed_when: result_i386_check.rc > 1
- name: Enable i386 architecture
  become: true
  ansible.builtin.command: dpkg --add-architecture i386
  when: result_i386_check.rc == 1
  changed_when: true

- name: Install Nvidia driver
  become: true
  ansible.builtin.apt:
    install_recommends: true
    update_cache: true
    name:
      - firmware-misc-nonfree
      - linux-headers-amd64
      - nvidia-driver
      - nvidia-driver-libs:i386
      - vainfo
      - vdpauinfo
