---
- name: Create groups
  become: true
  register: _podman_gitlab_groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
    system: true
  loop: "{{ podman_gitlab_groups }}"

- name: Ensure user is a group member
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ podman_gitlab_groups }}"
    append: true

- name: Create user
  become: true
  register: _podman_gitlab_user
  ansible.builtin.user:
    comment: "{{ podman_gitlab_name }}"
    create_home: false
    group: "{{ _podman_gitlab_groups.results[0].gid }}"
    groups: "{{ podman_gitlab_groups }}"
    home: "{{ podman_gitlab_basedir }}"
    name: "{{ podman_gitlab_id }}"
    password: "!"
    shell: "/usr/sbin/nologin"
    system: true


- name: Ensure working directory exists
  become: true
  ansible.builtin.file:
    path: "{{ podman_gitlab_basedir }}"
    state: directory
    owner: "{{ _podman_gitlab_user.uid }}"
    group: "{{ _podman_gitlab_groups.results[0].gid }}"
    mode: "u=rwX,g=rX"
    recurse: true

- name: Ensure directories exist
  become: true
  ansible.builtin.file:
    path: "{{ podman_gitlab_basedir }}/{{ item }}"
    state: directory
    owner: "{{ _podman_gitlab_user.uid }}"
    group: "{{ _podman_gitlab_groups.results[0].gid }}"
    mode: "u=rwX,g=rX"
    recurse: true
  loop:
    - config
    - data
    - logs

- name: Ensure working directory exists
  become: true
  ansible.builtin.file:
    path: "{{ podman_gitlab_runner_basedir }}"
    state: directory
    owner: "{{ _podman_gitlab_user.uid }}"
    group: "{{ _podman_gitlab_groups.results[0].gid }}"
    mode: "u=rwX,g=rX"
    recurse: true

- name: Ensure directories exist
  become: true
  ansible.builtin.file:
    path: "{{ podman_gitlab_runner_basedir }}/{{ item }}"
    state: directory
    owner: "{{ _podman_gitlab_user.uid }}"
    group: "{{ _podman_gitlab_groups.results[0].gid }}"
    mode: "u=rwX,g=rX"
    recurse: true
  loop:
    - config


- name: Copy service files
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ directory_systemd }}/{{ item }}"
    owner: root
    group: root
    mode: "0o644"
  loop:
    - gitlab-runner.service
    - gitlab.service

- name: Enable and check gitlab service
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    name: gitlab
    state: restarted
