---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Europe/Berlin
  METALLB_LB_RANGE: 192.168.178.227-192.168.178.237
  METALLB_K8S_GATEWAY_ADDR: 192.168.178.227
  METALLB_INGRESS_ADDR: 192.168.178.228
