---
- name: Set hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Configure podman
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/etc/containers/containers.conf"
    dest: /etc/containers/containers.conf
    owner: root
    group: root
    mode: "0o644"

- name: "Create network: labnet"
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/etc/systemd/network/labnet.network"
    dest: "{{ directory_networkd }}/labnet.network"
    owner: root
    group: root
    mode: "0o644"

- name: Configure DNS
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/etc/systemd/resolved.conf"
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root
    mode: "0o644"

- name: Steam
  ansible.builtin.include_tasks: steam.yml