---
- name: Create groups
  become: true
  register: _groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
    system: true
  loop: "{{ podman_nexus_groups }}"
  notify: Restart nexus

- name: Ensure user is a group member
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ podman_nexus_groups }}"
    append: true
  notify: Restart nexus

- name: Create user
  become: true
  register: _user
  ansible.builtin.user:
    comment: "{{ podman_nexus_name }}"
    create_home: false
    group: "{{ _groups.results[0].gid }}"
    groups: "{{ podman_nexus_groups }}"
    home: "{{ podman_nexus_basedir }}"
    name: "{{ podman_nexus_id }}"
    password: "!"
    shell: "/usr/sbin/nologin"
    system: true
  notify: Restart nexus


- name: Ensure working directory exists
  become: true
  ansible.builtin.file:
    path: "{{ podman_nexus_basedir }}"
    state: directory
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"
    mode: "0o750"
  notify: Restart nexus

- name: Ensure directories exist
  become: true
  ansible.builtin.file:
    path: "{{ podman_nexus_basedir }}/{{ item }}"
    state: directory
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"
    mode: "0o750"
  loop:
    - data
    - etc
    - etc/fabric
  notify: Restart nexus


- name: Create postgres user
  register: result
  retries: 3
  delay: 3
  until: result is not failed
  community.postgresql.postgresql_user:
    host: localhost
    login_password: "{{ podman_postgres_master_password }}"
    login_user: "{{ podman_postgres_master_user }}"
    name: "{{ podman_nexus_pg_user }}"
    password: "{{ podman_nexus_pg_password }}"

- name: Create postgres database
  register: result
  retries: 3
  delay: 3
  until: result is not failed
  community.postgresql.postgresql_db:
    encoding: UTF-8
    host: localhost
    login_password: "{{ podman_postgres_master_password }}"
    login_user: "{{ podman_postgres_master_user }}"
    name: "{{ podman_nexus_pg_db }}"
    owner: "{{ podman_nexus_pg_user }}"

- name: "GRANT ALL PRIVILEGES ON DATABASE 'db' TO 'user'"
  community.postgresql.postgresql_privs:
    host: localhost
    login_password: "{{ podman_postgres_master_password }}"
    login_user: "{{ podman_postgres_master_user }}"
    db: postgres
    privs: ALL
    type: database
    obj: "{{ podman_nexus_pg_db }}"
    role: "{{ podman_nexus_pg_user }}"

- name: "GRANT USAGE, CREATE ON SCHEMA PUBLIC TO 'user'"
  community.postgresql.postgresql_privs:
    host: localhost
    login_password: "{{ podman_postgres_master_password }}"
    login_user: "{{ podman_postgres_master_user }}"
    db: postgres
    privs: CREATE
    type: schema
    obj: public
    role: "{{ podman_nexus_pg_user }}"


- name: Copy storage configuration
  become: true
  ansible.builtin.template:
    src: nexus-store.properties.j2
    dest: "{{ podman_nexus_basedir }}/etc/fabric/nexus-store.properties"
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"
    mode: "0o640"
- name: Copy Nexus configuration
  become: true
  ansible.builtin.copy:
    src: nexus.properties
    dest: "{{ podman_nexus_basedir }}/etc/nexus.properties"
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"
    mode: "0o640"


- name: Pull service image
  become: true
  register: result
  retries: 3
  delay: 3
  until: result is not failed
  containers.podman.podman_image:
    name: "docker.io/sonatype/nexus3:{{ podman_nexus_version }}"

- name: Copy service files
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ directory_systemd }}/{{ item }}"
    owner: root
    group: root
    mode: "0o644"
  loop:
    - nexus.service
  notify: Restart nexus

- name: Enable and check service
  become: true
  ansible.builtin.systemd:
    name: nexus
    enabled: true
  notify: Restart nexus
