---
- name: Create groups
  become: true
  register: _groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
    system: true
  loop: "{{ podman_nexus_groups }}"
  notify: Restart nexus

- name: Ensure user is a group member
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ podman_nexus_groups }}"
    append: true
  notify: Restart nexus

- name: Create user
  become: true
  register: _user
  ansible.builtin.user:
    comment: "{{ podman_nexus_name }}"
    create_home: false
    group: "{{ _groups.results[0].gid }}"
    groups: "{{ podman_nexus_groups }}"
    home: "{{ podman_nexus_basedir }}"
    name: "{{ podman_nexus_id }}"
    password: "!"
    shell: "/usr/sbin/nologin"
    system: true
  notify: Restart nexus


- name: Ensure working directory exists
  become: true
  ansible.builtin.file:
    path: "{{ podman_nexus_basedir }}"
    state: directory
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"
    mode: "u=rwX,g=rX"
    recurse: true
  notify: Restart nexus

- name: Ensure directories exist
  become: true
  ansible.builtin.file:
    path: "{{ podman_nexus_basedir }}/{{ item }}"
    state: directory
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"
    mode: "u=rwX,g=rX"
    recurse: true
  loop:
    - data
  notify: Restart nexus


- name: Pull service image
  become: true
  register: result
  retries: 3
  delay: 3
  until: result is not failed
  containers.podman.podman_image:
    name: "docker.io/sonatype/nexus3:{{ podman_nexus_version }}"

- name: Copy service files
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ directory_systemd }}/{{ item }}"
    owner: root
    group: root
    mode: "0o644"
  loop:
    - nexus.service
  notify: Restart nexus

- name: Enable and check service
  become: true
  ansible.builtin.systemd:
    name: nexus
    enabled: true
  notify: Restart nexus
