---
- name: Install ddclient
  become: true
  ansible.builtin.apt:
    name:
      - ddclient
    update_cache: true

- name: Copy ddclient config file
  become: true
  ansible.builtin.template:
    src: "ddclient.conf.j2"
    dest: "/etc/ddclient.conf"
    owner: root
    group: root
    mode: 0600

- name: Create ddclient service
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/ddclient.service"
    dest: "{{ directory_systemd }}/ddclient.service"
    mode: 0644

- name: Enable and check ddclient service
  become: true
  ansible.builtin.systemd:
    name: ddclient
    daemon_reload: yes
    state: restarted
    enabled: yes
