media_credentials_file: ENC[AES256_GCM,data:q1JKef6ipbZoSymbSEntsNWm+NAmky8E2dBtEw==,iv:pBFv6QPjeP3f94jZrmkTSnQX9htVpzQ34cC2d5NrS/Q=,tag:tMCzygjgqMEWRRiuCOb2Mw==,type:str]
media_username: ENC[AES256_GCM,data:ejGfZQ0vsg==,iv:zQl92ekx3rdWRqGe6BLd65unC7frppkavzvMJq4C44k=,tag:9aszT3r/tknsd4PqUxoCSQ==,type:str]
media_password: ENC[AES256_GCM,data:X+58UwohzQ==,iv:A0RIkWEJ8dYSlJXzMeiDEmr3mKhLbDRwc97Ka1gR5A4=,tag:Qfj8LceG3KSgk4yoRshNag==,type:str]
media_ip_address: ENC[AES256_GCM,data:B0aXW6bSNnqaIN8yWA==,iv:OiQXUoiOzdVqCrxC8dRrVsmslMBjtiGNJiZPndpfvIU=,tag:C1wplBVnd9IMuHDQ0t2ADg==,type:str]
media_location: ENC[AES256_GCM,data:dZ6qzXbtWUYGX/tIuNLYGnHqCeBIhys=,iv:r5odFEcEN4TRDJ1pXPRkvikWAL5o5TNXTgqIwp/lLyc=,tag:n26slFMNI2H8GUV1LiKrOQ==,type:str]
media_mount: ENC[AES256_GCM,data:4jLye85Z3Z/1dhI8,iv:ZOFXAUBVs5WSEV9kaEuQTRj+nyUsphJgTqIoiicCZvA=,tag:mf2NaftzcKpYkMnY6umSuw==,type:str]
media_wol_address: ENC[AES256_GCM,data:G+uHVl1gHPlLWIKQdkIOqoI=,iv:PdL5zNW/FzlHbcHMSglL37lrP7LwYZCmQ14yscNPDGM=,tag:AGQFkHXTQg9WZ27+DLfQqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pan98cxr43vkcty4lr2krz0lv9tcfh48dl29vft28jv54txyts7qcxwshn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ODA5aWdkTzZvSVBzeHpH
            YUt4blB0U2lqQ1V1TE1NMVFXZGVIdGk1UFZjCitUeHViNW5wekZmQ2x5MDNwQjVi
            YW91clVZZjYrYTVtOVRIK2RvZHdiSjAKLS0tIEluT2hWaG9KWFBMZWdyOU53RnAy
            ei9iam02cWZOTjBEK0JiM2VJNlh4OVkKOcd8+wLEG/May3gaiwT+4oqg49vCuYbN
            MOQLSBXhiMD5KLPlpDBDgCB0td6Ulh7QlcjSwXWUGhDDDykAMh0OZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-03T18:20:58Z"
    mac: ENC[AES256_GCM,data:BLFDTslVjO77/mXqRbkZIZ685Adw3uinMk+gBy3RUp2fhhi1CZKJAgRlyc0i8Q8ODRfIbh8v39r29nR1IheTMhIYphs+QqBoFJphTXNdHWyTFjA8+2ob1nf/LbmU2cH85PdGKrr8AP9p2DiH3RZeekIf0/GzIdv0DrB3iH/n8TA=,iv:BMIi8MhSRIeIE+ZwYHreNZTHOHMdZpue/5t+TX5lfCc=,tag:PZF41YmxyxYRv6vrTN+2aw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
