media_username: ENC[AES256_GCM,data:ejGfZQ0vsg==,iv:zQl92ekx3rdWRqGe6BLd65unC7frppkavzvMJq4C44k=,tag:9aszT3r/tknsd4PqUxoCSQ==,type:str]
media_password: ENC[AES256_GCM,data:X+58UwohzQ==,iv:A0RIkWEJ8dYSlJXzMeiDEmr3mKhLbDRwc97Ka1gR5A4=,tag:Qfj8LceG3KSgk4yoRshNag==,type:str]
media_ip_address: ENC[AES256_GCM,data:B0aXW6bSNnqaIN8yWA==,iv:OiQXUoiOzdVqCrxC8dRrVsmslMBjtiGNJiZPndpfvIU=,tag:C1wplBVnd9IMuHDQ0t2ADg==,type:str]
media_location: ENC[AES256_GCM,data:dZ6qzXbtWUYGX/tIuNLYGnHqCeBIhys=,iv:r5odFEcEN4TRDJ1pXPRkvikWAL5o5TNXTgqIwp/lLyc=,tag:n26slFMNI2H8GUV1LiKrOQ==,type:str]
media_mount: ENC[AES256_GCM,data:4jLye85Z3Z/1dhI8,iv:ZOFXAUBVs5WSEV9kaEuQTRj+nyUsphJgTqIoiicCZvA=,tag:mf2NaftzcKpYkMnY6umSuw==,type:str]
media_wol_address: ENC[AES256_GCM,data:G+uHVl1gHPlLWIKQdkIOqoI=,iv:PdL5zNW/FzlHbcHMSglL37lrP7LwYZCmQ14yscNPDGM=,tag:AGQFkHXTQg9WZ27+DLfQqA==,type:str]
podman_oauth2proxy_client_secret: ENC[AES256_GCM,data:RuSPriObGTRCE3EXePuiwM7kFzVJfhx+B0LMxcFK/nQ=,iv:45fksWnEoaJ4C1XDQV2ZXbfsKzjsB2Tqb6mWmx5A9Dk=,tag:URDllPdLm1yAGDcQEgvKyw==,type:str]
podman_oauth2proxy_cookie_secret: ENC[AES256_GCM,data:YctGCWrF4bdb5AP7AFoYhclP6j/al4/F,iv:lbNJtJq8OjKXkgCO+eqYySpw9x4WNMLhXAaSqDomoyc=,tag:YjedqGBQsDZfoBOjgxXzNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pan98cxr43vkcty4lr2krz0lv9tcfh48dl29vft28jv54txyts7qcxwshn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ODA5aWdkTzZvSVBzeHpH
            YUt4blB0U2lqQ1V1TE1NMVFXZGVIdGk1UFZjCitUeHViNW5wekZmQ2x5MDNwQjVi
            YW91clVZZjYrYTVtOVRIK2RvZHdiSjAKLS0tIEluT2hWaG9KWFBMZWdyOU53RnAy
            ei9iam02cWZOTjBEK0JiM2VJNlh4OVkKOcd8+wLEG/May3gaiwT+4oqg49vCuYbN
            MOQLSBXhiMD5KLPlpDBDgCB0td6Ulh7QlcjSwXWUGhDDDykAMh0OZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-03T10:36:32Z"
    mac: ENC[AES256_GCM,data:xLzLQIw/TaIKA+e3HMiaxpF+EWqr2CyCoEVRorJVOLvFWbRNX+i0EsUkurmWRBnqs+Pub9DzxVgzJaBql4+f8ped3pXKszhgxggJUkuqhXaMuldgW41d1Tak77D3vi9GxI7TIYtx4YRh+EztwnD8r7dd/2Y7yTE4dOr37y5r4j8=,iv:2ETWWx2nfdV/ZtOkyH2iI8KM/+0P8HTpngmKvcpda30=,tag:d43P+JQG/d3dtD2391bc6g==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
