podman_service_network_subnet: "10.100.26.0/24"
podman_service_network_gateway: "10.100.26.1"

kvm_up_nets:
  domain:
    net_template: network-template
    title: Labnet Local Domain
    description: Labnet Local Domain Network
    nic: enp0s25

kvm_up_guests:
  media:
    vm_ram_mb: 16384
    vm_vcpus: 6
    vm_net: domain
    os_type: debian12
    file_type: qcow2
    base_image_name: debian-template
    vm_template: debian-template
    second_hdd: false
    second_hdd_size: ""
