---
- name: Ensure working directory exists
  become: true
  ansible.builtin.file:
    path: "{{ podman_ytdlsub_basedir }}"
    state: directory
    owner: 1001
    group: 1001
    mode: "0o644"

- name: Copy configuration
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ podman_ytdlsub_basedir }}/{{ item }}"
    owner: 1001
    group: 1001
    mode: "0o644"
    unsafe_writes: true
  loop:
    - config.yml
    - subscriptions.yml

- name: Copy service files
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ directory_systemd }}/{{ item }}"
    owner: root
    group: root
    mode: "0o644"
  loop:
    - ytdlsub.service

- name: Enable and check service
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    name: ytdlsub
    state: restarted
