---
- name: Create groups
  become: true
  register: _podman_sonarr_groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
    system: true
  loop: "{{ podman_sonarr_groups }}"
  notify: Restart sonarr

- name: Ensure user is a group member
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ podman_sonarr_groups }}"
    append: true
  notify: Restart sonarr

- name: Create user
  become: true
  register: _podman_sonarr_user
  ansible.builtin.user:
    comment: "{{ podman_sonarr_name }}"
    create_home: false
    group: "{{ _podman_sonarr_groups.results[0].gid }}"
    groups: "{{ podman_sonarr_groups }}"
    home: "{{ podman_sonarr_basedir }}"
    name: "{{ podman_sonarr_id }}"
    password: "!"
    shell: "/usr/sbin/nologin"
    system: true
  notify: Restart sonarr


- name: Ensure working directory exists
  become: true
  ansible.builtin.file:
    path: "{{ podman_sonarr_basedir }}"
    state: directory
    owner: "{{ _podman_sonarr_user.uid }}"
    group: "{{ _podman_sonarr_groups.results[0].gid }}"
    mode: "u=rwX,g=rX"
    recurse: true
  notify: Restart sonarr

- name: Ensure directories exist
  become: true
  ansible.builtin.file:
    path: "{{ podman_sonarr_basedir }}/{{ item }}"
    state: directory
    owner: "{{ _podman_sonarr_user.uid }}"
    group: "{{ _podman_sonarr_groups.results[0].gid }}"
    mode: "u=rwX,g=rX"
    recurse: true
  loop:
    - config
  notify: Restart sonarr


- name: Create postgres user
  register: podman_sonarr_result
  retries: 3
  delay: 3
  until: podman_sonarr_result is not failed
  community.postgresql.postgresql_user:
    host: localhost
    login_password: "{{ podman_postgres_master_password }}"
    login_user: "{{ podman_postgres_master_user }}"
    name: "{{ podman_sonarr_pg_user }}"
    password: "{{ podman_sonarr_pg_password }}"
  notify: Restart sonarr

- name: Create postgres database
  register: podman_sonarr_result
  retries: 3
  delay: 3
  until: podman_sonarr_result is not failed
  community.postgresql.postgresql_db:
    host: localhost
    login_password: "{{ podman_postgres_master_password }}"
    login_user: "{{ podman_postgres_master_user }}"
    name: "{{ podman_sonarr_pg_db }}-{{ item }}"
    owner: "{{ podman_sonarr_pg_user }}"
  loop:
    - main
    - log
  notify: Restart sonarr

- name: "GRANT ALL PRIVILEGES ON DATABASE 'db' TO 'user'"
  community.postgresql.postgresql_privs:
    host: localhost
    login_password: "{{ podman_postgres_master_password }}"
    login_user: "{{ podman_postgres_master_user }}"
    db: postgres
    privs: ALL
    type: database
    obj: "{{ podman_sonarr_pg_db }}-{{ item }}"
    role: "{{ podman_sonarr_pg_user }}"
  loop:
    - main
    - log
  notify: Restart sonarr

- name: "GRANT USAGE, CREATE ON SCHEMA PUBLIC TO 'user'"
  community.postgresql.postgresql_privs:
    host: localhost
    login_password: "{{ podman_postgres_master_password }}"
    login_user: "{{ podman_postgres_master_user }}"
    db: postgres
    privs: CREATE
    type: schema
    obj: public
    role: "{{ podman_sonarr_pg_user }}"
  notify: Restart sonarr


- name: Copy configuration
  become: true
  ansible.builtin.template:
    src: config.xml.j2
    dest: "{{ podman_sonarr_basedir }}/config/config.xml"
    owner: "{{ _podman_sonarr_user.uid }}"
    group: "{{ _podman_sonarr_groups.results[0].gid }}"
    mode: "0o644"
  notify: Restart sonarr


- name: Copy service files
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ directory_systemd }}/{{ item }}"
    owner: root
    group: root
    mode: "0o644"
  loop:
    - sonarr-exporter.service
    - sonarr-main.service
    - sonarr.service
  notify: Restart sonarr

- name: Enable and check sonarr service
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: sonarr
  notify: Restart sonarr
