---
- name: Ensure working directory exists
  ansible.builtin.file:
    path: "{{ downloads_directory }}/age"
    state: directory
    owner: "{{ ansible_user }}"

- name: Download age archive
  ansible.builtin.get_url:
    url: "https://github.com/FiloSottile/age/releases/download/v{{ version_age }}/age-v{{ version_age }}-linux-amd64.tar.gz"
    dest: "{{ downloads_directory }}"

- name: Extract age archive
  ansible.builtin.unarchive:
    src: "{{ downloads_directory }}/age-v1.0.0-linux-amd64.tar.gz"
    dest: "{{ downloads_directory }}"

- name: Copy age binary to destination directory
  become: true
  ansible.builtin.copy:
    src: "{{ downloads_directory }}/age/{{ item }}"
    dest: /usr/local/bin/{{ item }}
    mode: 0755
    owner: root
    group: root
    remote_src: true
  with_items: 
    - age
    - age-keygen
