---
- name: Ensure working directory exists
  ansible.builtin.file:
    path: "{{ directory_downloads }}"
    state: directory
    owner: "{{ ansible_user }}"

- name: Download Discord .deb
  ansible.builtin.get_url: 
    url: https://discord.com/api/download?platform=linux&format=deb
    dest: "{{ directory_downloads }}/discord.deb"

- name: Install Discord
  become: true
  ansible.builtin.apt: 
    deb: "{{ directory_downloads }}/discord.deb"
