---
- name: Download kubectl binary
  ansible.builtin.get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/v1.25.0/bin/linux/amd64/kubectl"
    dest: /tmp
    mode: 0600

- name: Copy kubectl binary to destination directory
  become: true
  ansible.builtin.copy:
    src: /tmp/kubectl
    dest: /usr/local/bin/kubectl
    mode: 0755
    owner: root
    group: root
    remote_src: true

- name: Check for kubeconfig
  delegate_to: localhost
  ansible.builtin.stat:
    path: kubeconfig
  register: stat_kubeconfig

- name: Create .kube folder
  ansible.builtin.file:
    path: ~{{ ansible_user }}/.kube
    state: directory
  when: stat_kubeconfig.stat.exists

- name: Copy kube config
  ansible.builtin.copy:
    src: kubeconfig
    dest: ~{{ ansible_user }}/.kube/config
  when: stat_kubeconfig.stat.exists
