- name: Create keyring storage
  become: true
  file:
    path: "{{ directory_keyrings }}"
    state: directory
- name: Install APT key
  become: true
  ansible.builtin.apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    keyring: "{{ directory_keyrings }}/oracle-virtualbox-2016.gpg"
    state: present

- name: Add Oracle VirtualBox Repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ directory_keyrings }}/oracle-virtualbox-2016.gpg] https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    state: present

- name: Install VirtualBox
  become: true
  ansible.builtin.apt:
    name:
      - virtualbox-7.0
    state: present
    update_cache: true

- name: Add user '{{ ansible_user }}' to VirtualBoxUsers group
  become: true
  ansible.builtin.user:
    name: '{{ ansible_user }}'
    groups: vboxusers
    append: true
