---
- name: Check if we have xfconf-query
  command: xfconf-query --version
  register: xfconf_query_check

- name: Set window scaling factor
  community.general.xfconf:
    channel: "xsettings"
    property: "/Gdk/WindowScalingFactor"
    value_type: "int"
    value: "2"
  when: xfconf_query_check.rc == 0

- name: Set window manager theme
  community.general.xfconf:
    channel: "xfwm4"
    property: "/general/theme"
    value_type: "string"
    value: "Default-xhdpi"
  when: xfconf_query_check.rc == 0

- name: Set theme
  community.general.xfconf:
    channel: xsettings
    property: /Net/ThemeName
    value_type: string
    value: Adwaita-dark
  when: xfconf_query_check.rc == 0

#- name: Don't save session on exit
#  community.general.xfconf:
#    channel: xfce4-session
#    property: /general/SaveOnExit
#    value_type: bool
#    value: "false"
# It's not clear why the above approach doesn't work, but it simply produces no changes.
# When we run the command manually, everything works as expected.
- name: Don't save session on exit (manual)
  ansible.builtin.command: xfconf-query -c xfce4-session -p /general/SaveOnExit -t bool -s false -n
  when: xfconf_query_check.rc == 0

- name: Copy .xsessionrc
  ansible.builtin.copy:
    src: "{{ role_path }}/files/home/.xsessionrc"
    dest: ~/.xsessionrc
  when: xfconf_query_check.rc == 0

- name: Install Terminal configuration
  ansible.builtin.copy:
    src: "{{ role_path }}/files/home/.config/xfce4/terminal/terminalrc"
    dest: ~/.config/xfce4/terminal/terminalrc
  when: xfconf_query_check.rc == 0

- name: Update font cache
  ansible.builtin.command: fc-cache -fv
  when: xfconf_query_check.rc == 0