---
- name: Create groups
  become: true
  register: _groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
    system: true
  loop: "{{ podman_recyclarr_groups }}"
  notify: Restart recyclarr

- name: Ensure user is a group member
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ podman_recyclarr_groups }}"
    append: true
  notify: Restart recyclarr

- name: Create user
  become: true
  register: _user
  ansible.builtin.user:
    comment: "{{ podman_recyclarr_name }}"
    create_home: false
    group: "{{ _groups.results[0].gid }}"
    groups: "{{ podman_recyclarr_groups }}"
    home: "{{ podman_recyclarr_basedir }}"
    name: "{{ podman_recyclarr_id }}"
    password: "!"
    shell: "/usr/sbin/nologin"
    system: true
  notify: Restart recyclarr


- name: Ensure working directory exists
  become: true
  ansible.builtin.file:
    path: "{{ podman_recyclarr_basedir }}"
    state: directory
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"
    mode: "u=rwX,g=rX"
    recurse: true
  notify: Restart recyclarr

- name: Ensure directories exist
  become: true
  ansible.builtin.file:
    path: "{{ podman_recyclarr_basedir }}/{{ item }}"
    state: directory
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"
    mode: "u=rwX,g=rX"
    recurse: true
  loop:
    - config
  notify: Restart recyclarr


- name: Copy configuration
  become: true
  ansible.builtin.template:
    src: "recyclarr.yml.j2"
    dest: "{{ podman_recyclarr_basedir }}/config/recyclarr.yml"
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"
    mode: "0o644"
  notify: Restart recyclarr


- name: Copy service files
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ directory_systemd }}/{{ item }}"
    owner: root
    group: root
    mode: "0o644"
  loop:
    - recyclarr-main.service
    - recyclarr.service
  notify: Restart recyclarr

- name: Enable and check recyclarr service
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: recyclarr
  notify: Restart recyclarr
