# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
    namespace: default
stringData:
    password: ENC[AES256_GCM,data:v77j4inlIo7QvvPVIIcurpGP/b4=,iv:bHd+MBaTOefIP9vilBK4Sec251NJmAxIAQU4iWwXbNw=,tag:8saygwtRm1r/V5+RMFKTxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19xq3hk7ylucjkrn3y83gzntr4e5agr2xka6y89aec5c474su5ggql973qy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLc1RhcUxySWJnekdRYTg0
            TTk1QmN5YTgrNkQrQ2tXeGZWMGVqSDlIUFNrCkN0dEtvTTBUc3ovR1dnMjlua1Bj
            QUp3ejJDcy84TUF5SEVtMityaHR2ZVUKLS0tIHBjd1NjS256aWpxWDRmeHFyOERh
            ck53bmUxWGNLNGc4bTNMR2lrbUlHcmcKza5kMGC+09HxLHUbf1/9yK1K7d24GNDd
            lfgq6ydgX78nxJAUia+x8trfyBz4qQBuii1AsVt4eZkLfc1HSyz1+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-08T11:08:48Z"
    mac: ENC[AES256_GCM,data:c1+qsVwO+9io85G8r/FfxdBuGM8bWdEmw0hlfZ16FqdzkpQ6wWw1rpegD7DsLBoG0Lsel2conGRsYn89jFsbkR2FTuOprc4JUFEKdhlRJKW0bYLlCbBkUloN5+n0mEGB5jgTHrZW14UYhT6adPOCQ27hkTtM63durYADmMw6hAg=,iv:q9nBHbqPJHonrTW679OHMfyUfPHDT0T9Rs1lntRYm1Y=,tag:rXSfCnBp8Az++Tl7xuij9A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
