apiVersion: v1
kind: Service
metadata:
  name: pihole-dns-tcp
  namespace: default
  labels:
    app: pihole
spec:
  type: NodePort
  ports:
    - name: dnstcp
      port: 53
      protocol: TCP
  selector:
    app: pihole
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns-udp
  namespace: default
  labels:
    app: pihole
spec:
  type: NodePort
  ports:
    - name: dnstcp
      port: 53
      protocol: UDP
  selector:
    app: pihole
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-http
  namespace: default
  labels:
    app: pihole
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
  selector:
    app: pihole