apiVersion: v1
kind: Service
metadata:
  name: pihole-dns-tcp
  namespace: default
  labels:
    app: pihole
spec:
  type: NodePort
  ports:
    - name: dnstcp
      port: 53
      protocol: TCP
  selector:
    app: pihole
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns-udp
  namespace: default
  labels:
    app: pihole
spec:
  type: LoadBalancer
  ports:
    - name: dnsudp
      port: 53
      protocol: UDP
  selector:
    app: pihole
  annotations:
    metallb.universe.tf/loadBalancerIPs: "${METALLB_K8S_GATEWAY_ADDR}"
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-http
  namespace: default
  labels:
    app: pihole
spec:
  type: NodePort
  ports:
    - name: http
      port: 8053
      protocol: TCP
      targetPort: 80
  selector:
    app: pihole