---
- name: Remove conflicting packages
  become: true
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Install dependencies
  become: true
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true

- name: Add Docker Repository
  become: true
  ansible.builtin.deb822_repository:
    name: docker
    types: [deb]
    uris: https://download.docker.com/linux/debian
    suites: ["{{ ansible_distribution_release }}"]
    components: [stable]
    signed_by: https://download.docker.com/linux/debian/gpg
    state: present
    enabled: true

- name: Install Docker
  become: true
  ansible.builtin.apt:
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Install docker python package
  become: true
  ansible.builtin.pip:
    name: docker

- name: Ensure /etc/docker exists
  become: true
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: "0o750"
- name: Enable IPv6 networking in Docker
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/etc/docker/daemon.json"
    dest: /etc/docker/daemon.json
    mode: "0o644"

- name: Add user to docker group
  become: true
  ansible.builtin.user:
    name: '{{ ansible_user }}'
    groups: docker
    append: true

- name: Enable and check docker service
  become: true
  ansible.builtin.systemd:
    name: docker
    daemon_reload: true
    state: restarted
    enabled: true

- name: Enable and check systemd-networkd service
  become: true
  ansible.builtin.systemd:
    name: systemd-networkd
    daemon_reload: true
    state: started
    enabled: true

- name: Enable and check systemd-networkd-wait-online service
  become: true
  ansible.builtin.systemd:
    name: systemd-networkd-wait-online
    daemon_reload: true
    state: started
    enabled: true
