---
- name: Ensure working directory exists
  become: true
  ansible.builtin.file:
    path: "{{ pihole_basedir }}"
    state: directory
    owner: "{{ ansible_user }}"

- name: Forward the host DNS zone to the aardvark DNS backend on the host
  become: true
  ansible.builtin.template:
    src: "20-forward-host-realm.conf.j2"
    dest: "{{ pihole_basedir }}/etc/dnsmasq.d/20-forward-host-realm.conf"
    mode: 0644

- name: Copy custom hosts list
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/custom.list"
    dest: "{{ pihole_basedir }}/etc/pihole/custom.list"
    mode: 0644

- name: Copy pihole service file
  become: true
  ansible.builtin.template:
    src: "pihole.service.j2"
    dest: "{{ directory_systemd }}/pihole.service"
    owner: root
    group: root
    mode: 0644

- name: Enable and check pihole service
  become: true
  ansible.builtin.systemd:
    name: pihole
    daemon_reload: true
    state: restarted
    enabled: true
