---
- name: Create groups
  become: true
  register: _groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
    system: true
  loop: "{{ pihole_groups }}"

- name: Ensure {{ ansible_user }} is a group member
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ pihole_groups }}"
    append: true

- name: Create user
  become: true
  register: _user
  ansible.builtin.user:
    comment: "{{ pihole_name }}"
    create_home: false
    group: "{{ _groups.results[0].gid }}"
    groups: "{{ pihole_groups }}"
    home: "{{ pihole_basedir }}"
    name: "{{ pihole_id }}"
    password: "!"
    shell: "/usr/sbin/nologin"
    system: true


- name: Ensure working directory exists
  become: true
  ansible.builtin.file:
    path: "{{ pihole_basedir }}"
    state: directory
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"

- name: Ensure directories exist
  become: true
  ansible.builtin.file:
    path: "{{ pihole_basedir }}/{{ item }}"
    state: directory
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"
  loop:
    - etc


- name: Forward the host DNS zone to the aardvark DNS backend on the host
  become: true
  ansible.builtin.template:
    src: "20-forward-host-realm.conf.j2"
    dest: "{{ pihole_basedir }}/etc/dnsmasq.d/20-forward-host-realm.conf"
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"
    mode: 0644

- name: Copy custom hosts list
  become: true
  ansible.builtin.copy:
    src: "custom.list"
    dest: "{{ pihole_basedir }}/etc/pihole/custom.list"
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"
    mode: 0644


- name: Create secret pihole_webpassword
  become: true
  containers.podman.podman_secret:
    data: "{{ pihole_webpassword }}"
    force: true
    name: pihole_webpassword
    state: present


- name: Copy service files
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ directory_systemd }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - pihole.service

- name: Enable and check service
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    name: pihole
    state: restarted
