---
- name: Copy pihole service file
  become: true
  ansible.builtin.template:
    src: "pihole.service.j2"
    dest: "{{ directory_systemd }}/pihole.service"
    owner: root
    group: root
    mode: 0644

- name: Enable and check pihole service
  become: true
  ansible.builtin.systemd:
    name: pihole
    daemon_reload: yes
    state: restarted
    enabled: yes
