---
- name: Ensure working directory exists
  become: true
  ansible.builtin.file:
    path: "{{ pihole_basedir }}"
    state: directory
    owner: "{{ ansible_user }}"

- name: Copy dnsmasq bind address fix
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/20-fix-binds.conf"
    dest: "{{ pihole_basedir }}/etc/dnsmasq.d/20-fix-binds.conf"
    mode: 0644

- name: Copy pihole service file
  become: true
  ansible.builtin.template:
    src: "pihole.service.j2"
    dest: "{{ directory_systemd }}/pihole.service"
    owner: root
    group: root
    mode: 0644

- name: Enable and check pihole service
  become: true
  ansible.builtin.systemd:
    name: pihole
    daemon_reload: true
    state: restarted
    enabled: true
