---
- name: Create podman service network
  containers.podman.podman_network:
    name: service
    ipv6: false
    ip_range: "{{ podman_service_network_ip_range }}"
    subnet: "{{ podman_service_network_subnet }}"
    gateway: "{{ podman_service_network_gateway }}"
  become: true
