---
- name: Install podman
  become: true
  ansible.builtin.apt:
    name: podman

- name: Create podman service network
  containers.podman.podman_network:
    name: service
    ipv6: false
    force: true
    internal: false
    opt:
      isolate: true
    subnet: "{{ podman_service_network_subnet }}"
  become: true

- name: Create podman Proton network
  when: podman_proton_network_subnet is defined
  containers.podman.podman_network:
    name: proton
    ipv6: false
    force: true
    internal: false
    opt:
      isolate: true
    subnet: "{{ podman_proton_network_subnet }}"
  become: true
