---
- name: Create groups
  become: true
  register: _groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
    system: true
  loop: "{{ mattermost_groups }}"

- name: Ensure {{ ansible_user }} is a group member
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ mattermost_groups }}"
    append: true

- name: Create user
  become: true
  register: _user
  ansible.builtin.user:
    comment: "{{ mattermost_name }}"
    create_home: false
    group: "{{ _groups.results[0].gid }}"
    groups: "{{ mattermost_groups }}"
    home: "{{ mattermost_basedir }}"
    name: "{{ mattermost_id }}"
    password: "!"
    shell: "/usr/sbin/nologin"
    system: true


- name: Ensure working directory exists
  become: true
  ansible.builtin.file:
    path: "{{ mattermost_basedir }}"
    state: directory
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"

- name: Ensure directories exist
  become: true
  ansible.builtin.file:
    path: "{{ mattermost_basedir }}/{{ item }}"
    state: directory
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"
  loop:
    - config
    - data
    - logs
    - plugins
    - client/plugins
    - bleve-indexes


- name: Create postgres user
  register: result
  retries: 3
  delay: 3
  until: result is not failed
  community.postgresql.postgresql_user:
    host: localhost
    login_password: "{{ postgres_master_password }}"
    login_user: "{{ postgres_master_user }}"
    name: "{{ mattermost_pg_user }}"
    password: "{{ mattermost_pg_password }}"

- name: Create postgres database
  register: result
  retries: 3
  delay: 3
  until: result is not failed
  community.postgresql.postgresql_db:
    host: localhost
    login_password: "{{ postgres_master_password }}"
    login_user: "{{ postgres_master_user }}"
    name: "{{ mattermost_pg_db }}"
    owner: "{{ mattermost_pg_user }}"

- name: "GRANT ALL PRIVILEGES ON DATABASE 'db' TO 'user'"
  community.postgresql.postgresql_privs:
    host: localhost
    login_password: "{{ postgres_master_password }}"
    login_user: "{{ postgres_master_user }}"
    db: postgres
    privs: ALL
    type: database
    obj: "{{ mattermost_pg_db }}"
    role: "{{ mattermost_pg_user }}"

- name: "GRANT USAGE, CREATE ON SCHEMA PUBLIC TO 'user'"
  community.postgresql.postgresql_privs:
    host: localhost
    login_password: "{{ postgres_master_password }}"
    login_user: "{{ postgres_master_user }}"
    db: postgres
    privs: CREATE
    type: schema
    obj: public
    role: "{{ mattermost_pg_user }}"


- name: Copy service files
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ directory_systemd }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - mattermost.service

- name: Enable and check service
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    name: mattermost
    state: restarted
