---
- name: Enable non-free APT
  become: true
  ansible.builtin.command: apt-add-repository --yes non-free
- name: Enable non-free-firmware APT
  become: true
  ansible.builtin.command: apt-add-repository --yes non-free-firmware

- name: Install Intel driver
  become: true
  ansible.builtin.apt:
    name:
      - intel-gpu-tools
      - intel-media-va-driver-non-free 
      - vainfo
      - vdpauinfo
