---
- name: Debug
  ansible.builtin.debug:
    msg: '<host mac="{{ item.key }}" name="{{ item.value.name }}" ip="{{ item.value.ip }}"/>'
  loop: "{{ item.value.dhcp_reserve | dict2items }}"

- name: Define networks
  community.libvirt.virt_net:
    command: define
    name: "{{ item.key }}"
    xml: "{{ lookup('template', '{{ item.value.net_template }}.xml.j2') }}"
  become: true

- name: Start network
  community.libvirt.virt_net:
    command: create
    name: "{{ item.key }}"

- name: Auto-Start network on boot
  community.libvirt.virt_net:
    autostart: true
    name: "{{ item.key }}"
