---
- name: Ensure requirements are in place
  ansible.builtin.apt:
    name:
      - libguestfs-tools
      - python3-libvirt
    state: present
  become: true

- name: Get networks list
  community.libvirt.virt_net:
    command: list_nets
  register: existing_nets
  changed_when: false

- name: Get VMs list
  community.libvirt.virt:
    command: list_vms
  register: existing_vms
  changed_when: false

- name: Copy base image
  ansible.builtin.copy:
    dest: "{{ kvm_up_libvirt_pool_dir }}/{{ item.key }}.{{ item.value.file_type }}"
    src: "{{ kvm_up_libvirt_pool_dir }}/{{ item.value.base_image_name }}.{{ item.value.file_type }}"
    force: false
    remote_src: true
    mode: "0o660"
    group: libvirt-qemu
    owner: libvirt-qemu
  register: copy_results
  with_dict: "{{ kvm_up_guests }}"
  become: true

- name: Create missing networks
  ansible.builtin.include_tasks: create_nets.yml
  when: "item.key not in existing_nets.list_nets"
  with_dict: "{{ kvm_up_nets }}"

- name: Create missing VMs
  ansible.builtin.include_tasks: create_vms.yml
  when: "item.key not in existing_vms.list_vms"
  with_dict: "{{ kvm_up_guests }}"
