---
- name: Copy Jellyfin service file
  become: true
  ansible.builtin.template:
    src: "jellyfin.service.j2"
    dest: "{{ systemd_dir }}/jellyfin.service"
    owner: root
    group: root
    mode: 0755

- name: Enable and check Jellyfin service
  become: true
  ansible.builtin.systemd:
    name: jellyfin
    daemon_reload: yes
    state: restarted
    enabled: yes
