---
- name: Set hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: "Create network: labnet"
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/etc/systemd/network/labnet.network"
    dest: "{{ directory_networkd }}/labnet.network"
    owner: root
    group: root
    mode: "0o644"
  notify: Restart systemd-networkd

- name: Configure DNS
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/etc/systemd/resolved.conf"
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root
    mode: "0o644"
  notify: Restart systemd-resolved

- name: Create mounts
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/etc/systemd/system/{{ item }}"
    dest: "{{ directory_systemd }}/{{ item }}"
    mode: "0o644"
    owner: root
    group: root
  loop:
    - mnt-storage.automount
    - mnt-storage.mount
    - mnt-usb.automount
    - mnt-usb.mount
  notify: Reload systemd

- name: Configure mounts
  become: true
  ansible.builtin.systemd:
    enabled: false
    name: "{{ item }}"
    state: started
  loop:
    - mnt-storage.mount
    - mnt-usb.mount
  notify: Reload systemd

- name: Configure automounts
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: "{{ item }}"
  loop:
    - mnt-storage.automount
    - mnt-usb.automount
  notify: Reload systemd
