---
- name: Enable noswap service
  ansible.builtin.systemd:
    name: noswap
    state: started
    enabled: true
    daemon_reload: true

- name: Update dconf
  become: true
  ansible.builtin.command: dconf update
  changed_when: true
