---
- name: Enable noswap service
  ansible.builtin.systemd:
    name: noswap
    state: started
    enabled: true
    daemon_reload: true

- name: Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart systemd-resolved
  become: true
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
    enabled: true

- name: Restart systemd-networkd
  become: true
  ansible.builtin.systemd:
    name: systemd-networkd
    state: restarted
    enabled: true

- name: Enable Corepack
  become: true
  ansible.builtin.command: corepack enable
