---
- name: Enable noswap service
  ansible.builtin.systemd:
    name: noswap
    state: started
    enabled: true
    daemon_reload: true

- name: Enable Corepack
  become: true
  ansible.builtin.command: corepack enable
