---
- name: Install APT key
  become: true
  ansible.builtin.apt_key:
    url: https://packagecloud.io/golift/pkgs/gpgkey
    keyring: "{{ directory_keyrings }}/golift.gpg"
    state: present

- name: Add GoLift Repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ directory_keyrings }}/golift.gpg] https://packagecloud.io/golift/pkgs/ubuntu focal main"
    state: present

- name: Install Unpackerr
  become: true
  ansible.builtin.apt:
    name:
      - unpackerr
    state: present
    update_cache: true

- name: Copy Unpackerr configuration
  become: true
  ansible.builtin.template:
    src: unpackerr.conf.j2
    dest: "/etc/unpackerr/unpackerr.conf"
    owner: "unpackerr"
    group: "unpackerr"
    mode: "0o600"

- name: Ensure unpackerr is a group member
  become: true
  ansible.builtin.user:
    name: unpackerr
    groups: "{{ podman_qbittorrent_groups }}"
    append: true

# qBittorrent

- name: Create groups
  become: true
  register: _groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
    system: true
  loop: "{{ podman_qbittorrent_groups }}"

- name: Ensure user is a group member
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ podman_qbittorrent_groups }}"
    append: true

- name: Create user
  become: true
  register: _user
  ansible.builtin.user:
    comment: "{{ podman_qbittorrent_name }}"
    create_home: false
    group: "{{ _groups.results[0].gid }}"
    groups: "{{ podman_qbittorrent_groups }}"
    home: "{{ podman_qbittorrent_basedir }}"
    name: "{{ podman_qbittorrent_id }}"
    password: "!"
    shell: "/usr/sbin/nologin"
    system: true


- name: Ensure working directory exists
  become: true
  ansible.builtin.file:
    path: "{{ podman_qbittorrent_basedir }}"
    state: directory
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"
    mode: "0o750"

- name: Ensure directories exist
  become: true
  ansible.builtin.file:
    path: "{{ podman_qbittorrent_basedir }}/{{ item }}"
    state: directory
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"
    mode: "0o750"
  loop:
    - config
    - config/wireguard


- name: Copy wireguard configuration
  become: true
  ansible.builtin.template:
    src: wg0.conf.j2
    dest: "{{ podman_qbittorrent_basedir }}/config/wireguard/wg0.conf"
    owner: "{{ _user.uid }}"
    group: "{{ _groups.results[0].gid }}"
    mode: "0o600"


- name: Copy service files
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ directory_systemd }}/{{ item }}"
    owner: root
    group: root
    mode: "0o644"
  loop:
    - qbittorrent-exporter.service
    - qbittorrent-flood.service
    - qbittorrent-main.service
    - qbittorrent-natmap.service
    - qbittorrent-wg.service
    - qbittorrent.service

- name: Enable and check service
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    name: qbittorrent
    state: restarted
