---
- name: Converge
  hosts: clients
  tasks:
    - name: Testing role
      block:
        - name: Call role
          ansible.builtin.include_role:
            name: podman_pihole
            tasks_from: main.yml
      rescue:
        - name: get errors
          shell: journalctl -xeu pihole.service
          register: err_msg
        - name: Print error message to console
          debug:
            msg: "{{ err_msg.stdout }}"
