---
- name: Install pip3
  become: true
  ansible.builtin.apt:
    name: python3-pip

- name: Install kubernetes python package
  ansible.builtin.pip:
    name: kubernetes

- name: Bootstrap Flux in k8s cluster
  become: false
  kubernetes.core.k8s:
    definition: "{{ lookup('kubernetes.core.kustomize', dir='cluster/bootstrap') }}"
