---
- name: Copy traefik service file
  become: true
  ansible.builtin.template:
    src: "traefik.service.j2"
    dest: "{{ directory_systemd }}/traefik.service"
    owner: root
    group: root
    mode: 0644

- name: Enable and check traefik service
  become: true
  ansible.builtin.systemd:
    name: traefik
    daemon_reload: true
    state: restarted
    enabled: true
