---
- name: Enable High-DPI display scaling
  hosts: desktop_hidpi
  
  tasks:
  #- name: Set DPI for X
  #  community.general.xfconf:
  #    channel: "xsettings"
  #    property: "/Xft/DPI"
  #    value_type: "int"
  #    value: "192"

  - name: Set window scaling factor
    community.general.xfconf:
      channel: "xsettings"
      property: "/Gdk/WindowScalingFactor"
      value_type: "int"
      value: "2"

  - name: Set window manager theme
    community.general.xfconf:
      channel: "xfwm4"
      property: "/general/theme"
      value_type: "string"
      value: "Default-xhdpi"

- name: Coding Environment
  hosts: desktop
  roles:
  - role: gantsign.visual-studio-code
  tasks:
  - name: Install git
    become: yes
    ansible.builtin.apt:
      name:
        - git
        - openssh-client
      state: present
      update_cache: true
  - name: Configure git email
    community.general.git_config:
      name: user.email
      scope: global
      value: oliver.salzburg@gmail.com
  - name: Configure git name
    community.general.git_config:
      name: user.name
      scope: global
      value: Oliver Salzburg
  - name: Configure git pull strategy
    community.general.git_config:
      name: pull.rebase
      scope: global
      value: false

- name: KeePassXC
  hosts: desktop
  tasks:
  - name: Install KeePassXC
    become: yes
    ansible.builtin.apt:
      name:
        - keepassxc
      state: present
      update_cache: true

- name: Discord
  hosts: desktop
  tasks:
  - name: Download Discord .deb
    ansible.builtin.get_url: 
      url: https://discord.com/api/download?platform=linux&format=deb
      dest: /tmp/discord.deb
  - name: Install Discord
    become: yes
    ansible.builtin.apt: 
      deb: /tmp/discord.deb
