---
- name: Enable High-DPI display scaling
  hosts: desktop_hidpi
  
  tasks:
  #- name: Set DPI for X
  #  community.general.xfconf:
  #    channel: "xsettings"
  #    property: "/Xft/DPI"
  #    value_type: "int"
  #    value: "192"

  - name: Set window scaling factor
    community.general.xfconf:
      channel: "xsettings"
      property: "/Gdk/WindowScalingFactor"
      value_type: "int"
      value: "2"

  - name: Set window manager theme
    community.general.xfconf:
      channel: "xfwm4"
      property: "/general/theme"
      value_type: "string"
      value: "Default-xhdpi"

- name: Install packages commonly used on Desktop
  hosts: desktop
  roles:
  - role: gantsign.visual-studio-code
  tasks:
  - name: Install git
    become: yes
    ansible.builtin.apt:
      name:
        - git
        - openssh-client
      state: present
      update_cache: true
  - name: Configure git email
    community.general.git_config:
      name: user.email
      scope: global
      value: oliver.salzburg@gmail.com
  - name: Configure git name
    community.general.git_config:
      name: user.name
      scope: global
      value: Oliver Salzburg