---
- name: Configure system to use Nvidia GPU
  hosts: desktop_nvidia
  
  tasks:
  - name: Install X server development package
    ansible.builtin.apt:
      name: xserver-xorg-devel
      state: present
      update_cache: true

  - name: Generate default X configuration
    ansible.builtin.shell: nvidia-xconfig
