---
- name: Configure system to use Nvidia GPU
  hosts: desktop_nvidia
  
  tasks:
  - name: Install dependencies
    become: true
    ansible.builtin.apt:
      name:
        - linux-headers-amd64
        - software-properties-common

  - name: Enable non-free APT
    become: true
    ansible.builtin.command: apt-add-repository non-free
  - name: Enable contrib APT
    become: true
    ansible.builtin.command: apt-add-repository contrib

  - name: Install Nvidia driver
    become: true
    ansible.builtin.apt:
      update_cache: true
      name:
        - firmware-misc-nonfree
        - nvidia-driver