---
- name: Configure the shell on the system
  hosts: all

  tasks:
    - name: Install vim
      become: true
      ansible.builtin.apt:
        name:
          - vim
    - name: Set default editor
      become: true
      community.general.alternatives:
        name: editor
        path: /usr/bin/vim

    - name: Copy .bashrc
      ansible.builtin.copy:
        src: ../home/.bashrc
        dest: ~/.bashrc
    - name: Copy .profile
      ansible.builtin.copy:
        src: ../home/.profile
        dest: ~/.profile

    - name: Install dependencies
      become: true
      ansible.builtin.apt:
        name:
          - keychain
          - ncdu
          - zsh

    - name: Download Oh My Zsh installer
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/install-ohmyzsh.sh
        mode: 0744
    - name: Execute the installer
      ansible.builtin.shell: 
        cmd: /tmp/install-ohmyzsh.sh
        creates: ~/.oh-my-zsh/
    - name: Install Powerlevel10k theme
      ansible.builtin.git:
        repo: "https://github.com/romkatv/powerlevel10k.git"
        dest: ~/.oh-my-zsh/themes/powerlevel10k
        depth: 1
    - name: Install ZSH auto-suggestions plugin
      ansible.builtin.git:
        repo: "https://github.com/zsh-users/zsh-autosuggestions"
        dest: ~/.oh-my-zsh/plugins/zsh-autosuggestions
        depth: 1
    - name: Install ZSH syntax highlighting plugin
      ansible.builtin.git:
        repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
        dest: ~/.oh-my-zsh/plugins/zsh-syntax-highlighting
        depth: 1
    - name: Install .zshrc
      ansible.builtin.copy:
        src: ../home/.zshrc
        dest: ~/.zshrc
    - name: Install powerlevel10k config
      ansible.builtin.copy:
        src: ../home/.p10k.zsh
        dest: ~/.p10k.zsh

    - name: Set login shell
      become: true
      ansible.builtin.user:
        name: oliver
        shell: /bin/zsh

    - name: Install Meslo Nerd Font patched for Powerlevel10k
      ansible.builtin.copy:
        src: ../home/.local/share/fonts/
        dest: ~/.local/share/fonts/
        mode: 0644
    - name: Update font cache
      command: fc-cache -fv
