---
- name: Configure the shell on the system
  hosts: all

  roles:
    - role: gantsign.antigen
      users:
        - username: oliver
          antigen_libraries:
            - name: oh-my-zsh
          antigen_theme:
            name: romkatv/powerlevel10k
            url: https://github.com/romkatv/powerlevel10k.git
          antigen_bundles:
            - name: aws
            - name: command-not-found
            - name: git
            - name: pip
            - name: safe-paste
            - name: terraform
            - name: tig
            - name: zsh-autosuggestions
              url: zsh-users/zsh-autosuggestions
            - name: zsh-syntax-highlighting
              url: zsh-users/zsh-syntax-highlighting

  tasks:
    - name: Install powerlevel10k config
      ansible.builtin.copy:
        src: ../home/.p10k.zsh
        dest: ~/.p10k.zsh
