---
- name: Configure the shell on the system
  hosts: desktop

  tasks:
    - name: Set theme
      community.general.xfconf:
        channel: xsettings
        property: /Net/ThemeName
        value_type: string
        value: Adwaita-dark
    #- name: Don't save session on exit
    #  community.general.xfconf:
    #    channel: xfce4-session
    #    property: /general/SaveOnExit
    #    value_type: bool
    #    value: "false"
    # It's not clear why the above approach doesn't work, but it simply produces no changes.
    # When we run the command manually, everything works as expected.
    - name: Don't save session on exit (manual)
      ansible.builtin.command: xfconf-query -c xfce4-session -p /general/SaveOnExit -t bool -s false

    - name: Install Meslo Nerd Font patched for Powerlevel10k
      ansible.builtin.copy:
        src: ../home/.local/share/fonts/
        dest: ~/.local/share/fonts/
        mode: 0644
    - name: Update font cache
      command: fc-cache -fv

    - name: Copy .xsessionrc
      ansible.builtin.copy:
        src: ../home/.xsessionrc
        dest: ~/.xsessionrc
    - name: Install Terminal configuration
      ansible.builtin.copy:
        src: ../home/.config/xfce4/terminal/terminalrc
        dest: ~/.config/xfce4/terminal/terminalrc
