---
- name: Configure the shell on the system
  hosts: desktop

  tasks:
    - name: Install Meslo Nerd Font patched for Powerlevel10k
      ansible.builtin.copy:
        src: ../home/.local/share/fonts/
        dest: ~/.local/share/fonts/
        mode: 0644
    - name: Update font cache
      command: fc-cache -fv

    - name: Copy .xsessionrc
      ansible.builtin.copy:
        src: ../home/.xsessionrc
        dest: ~/.xsessionrc
    - name: Install Terminal configuration
      ansible.builtin.copy:
        src: ../home/.config/xfce4/terminal/terminalrc
        dest: ~/.config/xfce4/terminal/terminalrc
